# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
from . import rpc_serial_pb2 as _rpc_serial_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class RpcSerialStub:
    """Client-driven serial peer ("rpc-serial"): the RPC client is the device on the
    far end of the BBC's serial wire. The client injects bytes for the BBC to
    receive (Send) and collects bytes the BBC has transmitted (Receive). This
    service belongs to the rpc-serial PeripheralExtension, which owns the endpoint.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RpcSerialAsyncStub: ...
    Send: _grpc.UnaryUnaryMultiCallable[_rpc_serial_pb2.RpcSerialSendRequest, _rpc_serial_pb2.RpcSerialSendResponse]
    """Inject bytes for the BBC to receive (device -> Beeb)."""
    Receive: _grpc.UnaryUnaryMultiCallable[_rpc_serial_pb2.RpcSerialReceiveRequest, _rpc_serial_pb2.RpcSerialReceiveResponse]
    """Collect bytes the BBC has transmitted (Beeb -> device)."""
    GetStatus: _grpc.UnaryUnaryMultiCallable[_rpc_serial_pb2.RpcSerialStatusRequest, _rpc_serial_pb2.RpcSerialStatus]
    """Pending byte counts in each direction."""

@_typing.type_check_only
class RpcSerialAsyncStub(RpcSerialStub):
    """Client-driven serial peer ("rpc-serial"): the RPC client is the device on the
    far end of the BBC's serial wire. The client injects bytes for the BBC to
    receive (Send) and collects bytes the BBC has transmitted (Receive). This
    service belongs to the rpc-serial PeripheralExtension, which owns the endpoint.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Send: _aio.UnaryUnaryMultiCallable[_rpc_serial_pb2.RpcSerialSendRequest, _rpc_serial_pb2.RpcSerialSendResponse]  # type: ignore[assignment]
    """Inject bytes for the BBC to receive (device -> Beeb)."""
    Receive: _aio.UnaryUnaryMultiCallable[_rpc_serial_pb2.RpcSerialReceiveRequest, _rpc_serial_pb2.RpcSerialReceiveResponse]  # type: ignore[assignment]
    """Collect bytes the BBC has transmitted (Beeb -> device)."""
    GetStatus: _aio.UnaryUnaryMultiCallable[_rpc_serial_pb2.RpcSerialStatusRequest, _rpc_serial_pb2.RpcSerialStatus]  # type: ignore[assignment]
    """Pending byte counts in each direction."""

class RpcSerialServicer(metaclass=_abc_1.ABCMeta):
    """Client-driven serial peer ("rpc-serial"): the RPC client is the device on the
    far end of the BBC's serial wire. The client injects bytes for the BBC to
    receive (Send) and collects bytes the BBC has transmitted (Receive). This
    service belongs to the rpc-serial PeripheralExtension, which owns the endpoint.
    """

    @_abc_1.abstractmethod
    def Send(
        self,
        request: _rpc_serial_pb2.RpcSerialSendRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_rpc_serial_pb2.RpcSerialSendResponse, _abc.Awaitable[_rpc_serial_pb2.RpcSerialSendResponse]]:
        """Inject bytes for the BBC to receive (device -> Beeb)."""

    @_abc_1.abstractmethod
    def Receive(
        self,
        request: _rpc_serial_pb2.RpcSerialReceiveRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_rpc_serial_pb2.RpcSerialReceiveResponse, _abc.Awaitable[_rpc_serial_pb2.RpcSerialReceiveResponse]]:
        """Collect bytes the BBC has transmitted (Beeb -> device)."""

    @_abc_1.abstractmethod
    def GetStatus(
        self,
        request: _rpc_serial_pb2.RpcSerialStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_rpc_serial_pb2.RpcSerialStatus, _abc.Awaitable[_rpc_serial_pb2.RpcSerialStatus]]:
        """Pending byte counts in each direction."""

def add_RpcSerialServicer_to_server(servicer: RpcSerialServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...