# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HostSerialGetConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HostSerialGetConfigRequest: _TypeAlias = HostSerialGetConfigRequest  # noqa: Y015

@_typing.final
class HostSerialConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODE_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    BAUD_FIELD_NUMBER: _builtins.int
    SERIAL_OPEN_FIELD_NUMBER: _builtins.int
    OPEN_ERROR_FIELD_NUMBER: _builtins.int
    mode: _builtins.str
    """"pty" | "device" """
    path: _builtins.str
    """pty slave path, or the opened device path"""
    baud: _builtins.int
    """host line speed (device mode; informational for pty)"""
    serial_open: _builtins.bool
    """is the host port currently open?"""
    open_error: _builtins.str
    """OS error text when serial_open is false"""
    def __init__(
        self,
        *,
        mode: _builtins.str = ...,
        path: _builtins.str = ...,
        baud: _builtins.int = ...,
        serial_open: _builtins.bool = ...,
        open_error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["baud", b"baud", "mode", b"mode", "open_error", b"open_error", "path", b"path", "serial_open", b"serial_open"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HostSerialConfig: _TypeAlias = HostSerialConfig  # noqa: Y015

@_typing.final
class HostSerialSetConfigRequest(_message.Message):
    """Partial update: each field is optional; only the present ones are applied,
    diffed against the current config.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MODE_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    BAUD_FIELD_NUMBER: _builtins.int
    mode: _builtins.str
    """Only "device" is settable at runtime; "pty" is rejected (a pty can only be
    created at startup via --host-serial mode=pty). Any successful re-point
    results in device mode regardless, since the bridge opens a real device.
    """
    path: _builtins.str
    """the device path to open"""
    baud: _builtins.int
    """host line speed"""
    def __init__(
        self,
        *,
        mode: _builtins.str | None = ...,
        path: _builtins.str | None = ...,
        baud: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_baud", b"_baud", "_mode", b"_mode", "_path", b"_path", "baud", b"baud", "mode", b"mode", "path", b"path"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_baud", b"_baud", "_mode", b"_mode", "_path", b"_path", "baud", b"baud", "mode", b"mode", "path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__baud: _TypeAlias = _typing.Literal["baud"]  # noqa: Y015
    _WhichOneofArgType__baud: _TypeAlias = _typing.Literal["_baud", b"_baud"]  # noqa: Y015
    _WhichOneofReturnType__mode: _TypeAlias = _typing.Literal["mode"]  # noqa: Y015
    _WhichOneofArgType__mode: _TypeAlias = _typing.Literal["_mode", b"_mode"]  # noqa: Y015
    _WhichOneofReturnType__path: _TypeAlias = _typing.Literal["path"]  # noqa: Y015
    _WhichOneofArgType__path: _TypeAlias = _typing.Literal["_path", b"_path"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__baud) -> _WhichOneofReturnType__baud | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__mode) -> _WhichOneofReturnType__mode | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__path) -> _WhichOneofReturnType__path | None: ...

Global___HostSerialSetConfigRequest: _TypeAlias = HostSerialSetConfigRequest  # noqa: Y015