# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
from . import host_serial_pb2 as _host_serial_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class HostSerialStub:
    """Typed config API for the host-serial extension: query and re-point the host
    serial bridge (mode / path / baud) without going through the GUI ExtensionUi
    path. This service belongs to the host-serial PeripheralExtension and is
    present only when --host-serial is loaded. It drives the SAME underlying
    re-point path (HostSerialEndpoint::request_reopen) as the GUI editor, so a
    SetConfig and a GUI edit are equivalent and each is reflected in the other.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> HostSerialAsyncStub: ...
    GetConfig: _grpc.UnaryUnaryMultiCallable[_host_serial_pb2.HostSerialGetConfigRequest, _host_serial_pb2.HostSerialConfig]
    """Read the current bridge configuration and open state."""
    SetConfig: _grpc.UnaryUnaryMultiCallable[_host_serial_pb2.HostSerialSetConfigRequest, _host_serial_pb2.HostSerialConfig]
    """Re-point the bridge. A partial update: only the fields present in the
    request change; the rest are kept (the client sends just the diff). The
    re-point is applied asynchronously on the next emulation tick, so the
    returned config is a snapshot taken at call time and may still show the
    previous device until the re-point lands -- call GetConfig to confirm.
    """

@_typing.type_check_only
class HostSerialAsyncStub(HostSerialStub):
    """Typed config API for the host-serial extension: query and re-point the host
    serial bridge (mode / path / baud) without going through the GUI ExtensionUi
    path. This service belongs to the host-serial PeripheralExtension and is
    present only when --host-serial is loaded. It drives the SAME underlying
    re-point path (HostSerialEndpoint::request_reopen) as the GUI editor, so a
    SetConfig and a GUI edit are equivalent and each is reflected in the other.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetConfig: _aio.UnaryUnaryMultiCallable[_host_serial_pb2.HostSerialGetConfigRequest, _host_serial_pb2.HostSerialConfig]  # type: ignore[assignment]
    """Read the current bridge configuration and open state."""
    SetConfig: _aio.UnaryUnaryMultiCallable[_host_serial_pb2.HostSerialSetConfigRequest, _host_serial_pb2.HostSerialConfig]  # type: ignore[assignment]
    """Re-point the bridge. A partial update: only the fields present in the
    request change; the rest are kept (the client sends just the diff). The
    re-point is applied asynchronously on the next emulation tick, so the
    returned config is a snapshot taken at call time and may still show the
    previous device until the re-point lands -- call GetConfig to confirm.
    """

class HostSerialServicer(metaclass=_abc_1.ABCMeta):
    """Typed config API for the host-serial extension: query and re-point the host
    serial bridge (mode / path / baud) without going through the GUI ExtensionUi
    path. This service belongs to the host-serial PeripheralExtension and is
    present only when --host-serial is loaded. It drives the SAME underlying
    re-point path (HostSerialEndpoint::request_reopen) as the GUI editor, so a
    SetConfig and a GUI edit are equivalent and each is reflected in the other.
    """

    @_abc_1.abstractmethod
    def GetConfig(
        self,
        request: _host_serial_pb2.HostSerialGetConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_host_serial_pb2.HostSerialConfig, _abc.Awaitable[_host_serial_pb2.HostSerialConfig]]:
        """Read the current bridge configuration and open state."""

    @_abc_1.abstractmethod
    def SetConfig(
        self,
        request: _host_serial_pb2.HostSerialSetConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_host_serial_pb2.HostSerialConfig, _abc.Awaitable[_host_serial_pb2.HostSerialConfig]]:
        """Re-point the bridge. A partial update: only the fields present in the
        request change; the rest are kept (the client sends just the diff). The
        re-point is applied asynchronously on the next emulation tick, so the
        returned config is a snapshot taken at call time and may still show the
        previous device until the re-point lands -- call GetConfig to confirm.
        """

def add_HostSerialServicer_to_server(servicer: HostSerialServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...