# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: host_serial.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'host_serial.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11host_serial.proto\x12\x07\x62\x65\x65\x62ium\"\x1c\n\x1aHostSerialGetConfigRequest\"e\n\x10HostSerialConfig\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04\x62\x61ud\x18\x03 \x01(\r\x12\x13\n\x0bserial_open\x18\x04 \x01(\x08\x12\x12\n\nopen_error\x18\x05 \x01(\t\"p\n\x1aHostSerialSetConfigRequest\x12\x11\n\x04mode\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04path\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04\x62\x61ud\x18\x03 \x01(\rH\x02\x88\x01\x01\x42\x07\n\x05_modeB\x07\n\x05_pathB\x07\n\x05_baud2\xa6\x01\n\nHostSerial\x12K\n\tGetConfig\x12#.beebium.HostSerialGetConfigRequest\x1a\x19.beebium.HostSerialConfig\x12K\n\tSetConfig\x12#.beebium.HostSerialSetConfigRequest\x1a\x19.beebium.HostSerialConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'host_serial_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOSTSERIALGETCONFIGREQUEST']._serialized_start=30
  _globals['_HOSTSERIALGETCONFIGREQUEST']._serialized_end=58
  _globals['_HOSTSERIALCONFIG']._serialized_start=60
  _globals['_HOSTSERIALCONFIG']._serialized_end=161
  _globals['_HOSTSERIALSETCONFIGREQUEST']._serialized_start=163
  _globals['_HOSTSERIALSETCONFIGREQUEST']._serialized_end=275
  _globals['_HOSTSERIAL']._serialized_start=278
  _globals['_HOSTSERIAL']._serialized_end=444
# @@protoc_insertion_point(module_scope)