# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import scsi_host_adapter_pb2 as scsi__host__adapter__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scsi_host_adapter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScsiHostAdapterServiceStub(object):
    """Service for managing the Acorn SCSI host adapter and its attached targets.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTargets = channel.unary_unary(
                '/beebium.ScsiHostAdapterService/ListTargets',
                request_serializer=scsi__host__adapter__pb2.ListScsiTargetsRequest.SerializeToString,
                response_deserializer=scsi__host__adapter__pb2.ListScsiTargetsResponse.FromString,
                _registered_method=True)
        self.GetBusStatus = channel.unary_unary(
                '/beebium.ScsiHostAdapterService/GetBusStatus',
                request_serializer=scsi__host__adapter__pb2.GetScsiBusStatusRequest.SerializeToString,
                response_deserializer=scsi__host__adapter__pb2.GetScsiBusStatusResponse.FromString,
                _registered_method=True)
        self.WatchBusEvents = channel.unary_stream(
                '/beebium.ScsiHostAdapterService/WatchBusEvents',
                request_serializer=scsi__host__adapter__pb2.WatchScsiBusEventsRequest.SerializeToString,
                response_deserializer=scsi__host__adapter__pb2.ScsiBusEvent.FromString,
                _registered_method=True)


class ScsiHostAdapterServiceServicer(object):
    """Service for managing the Acorn SCSI host adapter and its attached targets.
    """

    def ListTargets(self, request, context):
        """List all SCSI targets (installed devices on the bus).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBusStatus(self, request, context):
        """Query the current SCSI bus state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchBusEvents(self, request, context):
        """Stream SCSI bus events in real-time. Events are emitted for phase
        transitions, commands dispatched, data transfers, and completion.
        The stream continues until the client disconnects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScsiHostAdapterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTargets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTargets,
                    request_deserializer=scsi__host__adapter__pb2.ListScsiTargetsRequest.FromString,
                    response_serializer=scsi__host__adapter__pb2.ListScsiTargetsResponse.SerializeToString,
            ),
            'GetBusStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusStatus,
                    request_deserializer=scsi__host__adapter__pb2.GetScsiBusStatusRequest.FromString,
                    response_serializer=scsi__host__adapter__pb2.GetScsiBusStatusResponse.SerializeToString,
            ),
            'WatchBusEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchBusEvents,
                    request_deserializer=scsi__host__adapter__pb2.WatchScsiBusEventsRequest.FromString,
                    response_serializer=scsi__host__adapter__pb2.ScsiBusEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.ScsiHostAdapterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.ScsiHostAdapterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScsiHostAdapterService(object):
    """Service for managing the Acorn SCSI host adapter and its attached targets.
    """

    @staticmethod
    def ListTargets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.ScsiHostAdapterService/ListTargets',
            scsi__host__adapter__pb2.ListScsiTargetsRequest.SerializeToString,
            scsi__host__adapter__pb2.ListScsiTargetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBusStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.ScsiHostAdapterService/GetBusStatus',
            scsi__host__adapter__pb2.GetScsiBusStatusRequest.SerializeToString,
            scsi__host__adapter__pb2.GetScsiBusStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchBusEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/beebium.ScsiHostAdapterService/WatchBusEvents',
            scsi__host__adapter__pb2.WatchScsiBusEventsRequest.SerializeToString,
            scsi__host__adapter__pb2.ScsiBusEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)