# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
from . import econet_pb2 as _econet_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class EconetServiceStub:
    """Econet/AUN networking management service.

    Provides hardware configuration (enable/disable Econet), network status
    queries (ADLC registers, handshake state), and AUN peer management.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> EconetServiceAsyncStub: ...
    GetEconetStatus: _grpc.UnaryUnaryMultiCallable[_econet_pb2.GetEconetStatusRequest, _econet_pb2.GetEconetStatusResponse]
    """Query Econet hardware status (enabled, station ID, ADLC state, peers)."""
    EnableEconet: _grpc.UnaryUnaryMultiCallable[_econet_pb2.EnableEconetRequest, _econet_pb2.EnableEconetResponse]
    """Fit Econet hardware: set station ID, optionally bind AUN socket."""
    DisableEconet: _grpc.UnaryUnaryMultiCallable[_econet_pb2.DisableEconetRequest, _econet_pb2.DisableEconetResponse]
    """Remove Econet hardware (disable station, close AUN socket)."""
    SetStationId: _grpc.UnaryUnaryMultiCallable[_econet_pb2.SetStationIdRequest, _econet_pb2.SetStationIdResponse]
    """Set the station ID (takes effect on next machine reset)."""
    SubscribeEconetEvents: _grpc.UnaryStreamMultiCallable[_econet_pb2.SubscribeEconetEventsRequest, _econet_pb2.EconetEvent]
    """Stream Econet events (frame activity, handshake changes, connection state).
    Reserved for future implementation.
    """
    WatchEconetStatus: _grpc.UnaryStreamMultiCallable[_econet_pb2.WatchEconetStatusRequest, _econet_pb2.GetEconetStatusResponse]
    """Server-pushed status stream. Writes an initial GetEconetStatusResponse
    as soon as the stream is established, then a fresh snapshot whenever
    status visible on EconetService changes (enable/disable, station ID
    change, or transport backend connection toggle). The stream stays open
    until the client cancels; use this instead of polling GetEconetStatus.
    """

@_typing.type_check_only
class EconetServiceAsyncStub(EconetServiceStub):
    """Econet/AUN networking management service.

    Provides hardware configuration (enable/disable Econet), network status
    queries (ADLC registers, handshake state), and AUN peer management.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetEconetStatus: _aio.UnaryUnaryMultiCallable[_econet_pb2.GetEconetStatusRequest, _econet_pb2.GetEconetStatusResponse]  # type: ignore[assignment]
    """Query Econet hardware status (enabled, station ID, ADLC state, peers)."""
    EnableEconet: _aio.UnaryUnaryMultiCallable[_econet_pb2.EnableEconetRequest, _econet_pb2.EnableEconetResponse]  # type: ignore[assignment]
    """Fit Econet hardware: set station ID, optionally bind AUN socket."""
    DisableEconet: _aio.UnaryUnaryMultiCallable[_econet_pb2.DisableEconetRequest, _econet_pb2.DisableEconetResponse]  # type: ignore[assignment]
    """Remove Econet hardware (disable station, close AUN socket)."""
    SetStationId: _aio.UnaryUnaryMultiCallable[_econet_pb2.SetStationIdRequest, _econet_pb2.SetStationIdResponse]  # type: ignore[assignment]
    """Set the station ID (takes effect on next machine reset)."""
    SubscribeEconetEvents: _aio.UnaryStreamMultiCallable[_econet_pb2.SubscribeEconetEventsRequest, _econet_pb2.EconetEvent]  # type: ignore[assignment]
    """Stream Econet events (frame activity, handshake changes, connection state).
    Reserved for future implementation.
    """
    WatchEconetStatus: _aio.UnaryStreamMultiCallable[_econet_pb2.WatchEconetStatusRequest, _econet_pb2.GetEconetStatusResponse]  # type: ignore[assignment]
    """Server-pushed status stream. Writes an initial GetEconetStatusResponse
    as soon as the stream is established, then a fresh snapshot whenever
    status visible on EconetService changes (enable/disable, station ID
    change, or transport backend connection toggle). The stream stays open
    until the client cancels; use this instead of polling GetEconetStatus.
    """

class EconetServiceServicer(metaclass=_abc_1.ABCMeta):
    """Econet/AUN networking management service.

    Provides hardware configuration (enable/disable Econet), network status
    queries (ADLC registers, handshake state), and AUN peer management.
    """

    @_abc_1.abstractmethod
    def GetEconetStatus(
        self,
        request: _econet_pb2.GetEconetStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_econet_pb2.GetEconetStatusResponse, _abc.Awaitable[_econet_pb2.GetEconetStatusResponse]]:
        """Query Econet hardware status (enabled, station ID, ADLC state, peers)."""

    @_abc_1.abstractmethod
    def EnableEconet(
        self,
        request: _econet_pb2.EnableEconetRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_econet_pb2.EnableEconetResponse, _abc.Awaitable[_econet_pb2.EnableEconetResponse]]:
        """Fit Econet hardware: set station ID, optionally bind AUN socket."""

    @_abc_1.abstractmethod
    def DisableEconet(
        self,
        request: _econet_pb2.DisableEconetRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_econet_pb2.DisableEconetResponse, _abc.Awaitable[_econet_pb2.DisableEconetResponse]]:
        """Remove Econet hardware (disable station, close AUN socket)."""

    @_abc_1.abstractmethod
    def SetStationId(
        self,
        request: _econet_pb2.SetStationIdRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_econet_pb2.SetStationIdResponse, _abc.Awaitable[_econet_pb2.SetStationIdResponse]]:
        """Set the station ID (takes effect on next machine reset)."""

    @_abc_1.abstractmethod
    def SubscribeEconetEvents(
        self,
        request: _econet_pb2.SubscribeEconetEventsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_econet_pb2.EconetEvent], _abc.AsyncIterator[_econet_pb2.EconetEvent]]:
        """Stream Econet events (frame activity, handshake changes, connection state).
        Reserved for future implementation.
        """

    @_abc_1.abstractmethod
    def WatchEconetStatus(
        self,
        request: _econet_pb2.WatchEconetStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_econet_pb2.GetEconetStatusResponse], _abc.AsyncIterator[_econet_pb2.GetEconetStatusResponse]]:
        """Server-pushed status stream. Writes an initial GetEconetStatusResponse
        as soon as the stream is established, then a fresh snapshot whenever
        status visible on EconetService changes (enable/disable, station ID
        change, or transport backend connection toggle). The stream stays open
        until the client cancels; use this instead of polling GetEconetStatus.
        """

def add_EconetServiceServicer_to_server(servicer: EconetServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...