# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
from . import extension_ui_pb2 as _extension_ui_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ExtensionUiServiceStub:
    """Extension UI framework: a small, server-driven UI vocabulary that lets
    any extension (peripheral, econet transport, future kinds) describe a
    control panel as a typed tree of Controls. Frontends render the tree
    natively and post user actions back through Dispatch.

    Design notes: docs/discussion/extension-ui-architecture.md

    The model is server-driven (Phoenix-LiveView style): the server holds
    the extension's state and computes a View; the client is a thin
    renderer with no business state. All user actions route through one
    Dispatch RPC -- there are no per-control RPCs.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ExtensionUiServiceAsyncStub: ...
    SubscribeView: _grpc.UnaryStreamMultiCallable[_extension_ui_pb2.SubscribeViewRequest, _extension_ui_pb2.View]
    """Open a long-lived stream of View updates for one extension. The
    server pushes a fresh View whenever the extension's state changes
    (the first View is delivered immediately on subscription). The
    stream ends with NOT_FOUND if the named extension does not exist
    (or is unloaded mid-session).
    """
    Dispatch: _grpc.UnaryUnaryMultiCallable[_extension_ui_pb2.DispatchRequest, _extension_ui_pb2.DispatchResponse]
    """Post a user action back to the server. The server validates the
    request (extension exists, control id is known for the current
    view revision, payload type matches the control type, revision is
    current) and then runs the extension's handle_event. The result of
    the action is observable on the SubscribeView stream as a new
    View, not in the response.
    """

@_typing.type_check_only
class ExtensionUiServiceAsyncStub(ExtensionUiServiceStub):
    """Extension UI framework: a small, server-driven UI vocabulary that lets
    any extension (peripheral, econet transport, future kinds) describe a
    control panel as a typed tree of Controls. Frontends render the tree
    natively and post user actions back through Dispatch.

    Design notes: docs/discussion/extension-ui-architecture.md

    The model is server-driven (Phoenix-LiveView style): the server holds
    the extension's state and computes a View; the client is a thin
    renderer with no business state. All user actions route through one
    Dispatch RPC -- there are no per-control RPCs.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    SubscribeView: _aio.UnaryStreamMultiCallable[_extension_ui_pb2.SubscribeViewRequest, _extension_ui_pb2.View]  # type: ignore[assignment]
    """Open a long-lived stream of View updates for one extension. The
    server pushes a fresh View whenever the extension's state changes
    (the first View is delivered immediately on subscription). The
    stream ends with NOT_FOUND if the named extension does not exist
    (or is unloaded mid-session).
    """
    Dispatch: _aio.UnaryUnaryMultiCallable[_extension_ui_pb2.DispatchRequest, _extension_ui_pb2.DispatchResponse]  # type: ignore[assignment]
    """Post a user action back to the server. The server validates the
    request (extension exists, control id is known for the current
    view revision, payload type matches the control type, revision is
    current) and then runs the extension's handle_event. The result of
    the action is observable on the SubscribeView stream as a new
    View, not in the response.
    """

class ExtensionUiServiceServicer(metaclass=_abc_1.ABCMeta):
    """Extension UI framework: a small, server-driven UI vocabulary that lets
    any extension (peripheral, econet transport, future kinds) describe a
    control panel as a typed tree of Controls. Frontends render the tree
    natively and post user actions back through Dispatch.

    Design notes: docs/discussion/extension-ui-architecture.md

    The model is server-driven (Phoenix-LiveView style): the server holds
    the extension's state and computes a View; the client is a thin
    renderer with no business state. All user actions route through one
    Dispatch RPC -- there are no per-control RPCs.
    """

    @_abc_1.abstractmethod
    def SubscribeView(
        self,
        request: _extension_ui_pb2.SubscribeViewRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_extension_ui_pb2.View], _abc.AsyncIterator[_extension_ui_pb2.View]]:
        """Open a long-lived stream of View updates for one extension. The
        server pushes a fresh View whenever the extension's state changes
        (the first View is delivered immediately on subscription). The
        stream ends with NOT_FOUND if the named extension does not exist
        (or is unloaded mid-session).
        """

    @_abc_1.abstractmethod
    def Dispatch(
        self,
        request: _extension_ui_pb2.DispatchRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_extension_ui_pb2.DispatchResponse, _abc.Awaitable[_extension_ui_pb2.DispatchResponse]]:
        """Post a user action back to the server. The server validates the
        request (extension exists, control id is known for the current
        view revision, payload type matches the control type, revision is
        current) and then runs the extension's handle_event. The result of
        the action is observable on the SubscribeView stream as a new
        View, not in the response.
        """

def add_ExtensionUiServiceServicer_to_server(servicer: ExtensionUiServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...