"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>

This file is part of Beebium.

Beebium is free software: you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version. Beebium is distributed in the hope that it will
be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Beebium.
If not, see <https://www.gnu.org/licenses/>.
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
from . import extension_rpc_pb2 as _extension_rpc_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ExtensionRpcStub:
    """The one generic, core-hosted service through which clients drive
    extension-provided APIs. Extensions never host a gRPC service themselves;
    they register C++ dispatchers and the core tunnels opaque serialized
    request/response bytes to them. This keeps the single gRPC runtime in the
    core, so a plugin never links gRPC. The extension's own request/response
    messages are ordinary protobuf, but they travel as opaque `payload` bytes
    here -- only the extension and the client (de)serialize them.

    See docs/discussion/extension-rpc-channel.md.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ExtensionRpcAsyncStub: ...
    Invoke: _grpc.UnaryUnaryMultiCallable[_extension_rpc_pb2.InvokeRequest, _extension_rpc_pb2.InvokeResponse]
    """Unary: one request, one response."""
    ServerStream: _grpc.UnaryStreamMultiCallable[_extension_rpc_pb2.InvokeRequest, _extension_rpc_pb2.InvokeResponse]
    """Server-streaming: one request, a stream of responses (status feeds,
    event subscriptions).
    """

@_typing.type_check_only
class ExtensionRpcAsyncStub(ExtensionRpcStub):
    """The one generic, core-hosted service through which clients drive
    extension-provided APIs. Extensions never host a gRPC service themselves;
    they register C++ dispatchers and the core tunnels opaque serialized
    request/response bytes to them. This keeps the single gRPC runtime in the
    core, so a plugin never links gRPC. The extension's own request/response
    messages are ordinary protobuf, but they travel as opaque `payload` bytes
    here -- only the extension and the client (de)serialize them.

    See docs/discussion/extension-rpc-channel.md.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Invoke: _aio.UnaryUnaryMultiCallable[_extension_rpc_pb2.InvokeRequest, _extension_rpc_pb2.InvokeResponse]  # type: ignore[assignment]
    """Unary: one request, one response."""
    ServerStream: _aio.UnaryStreamMultiCallable[_extension_rpc_pb2.InvokeRequest, _extension_rpc_pb2.InvokeResponse]  # type: ignore[assignment]
    """Server-streaming: one request, a stream of responses (status feeds,
    event subscriptions).
    """

class ExtensionRpcServicer(metaclass=_abc_1.ABCMeta):
    """The one generic, core-hosted service through which clients drive
    extension-provided APIs. Extensions never host a gRPC service themselves;
    they register C++ dispatchers and the core tunnels opaque serialized
    request/response bytes to them. This keeps the single gRPC runtime in the
    core, so a plugin never links gRPC. The extension's own request/response
    messages are ordinary protobuf, but they travel as opaque `payload` bytes
    here -- only the extension and the client (de)serialize them.

    See docs/discussion/extension-rpc-channel.md.
    """

    @_abc_1.abstractmethod
    def Invoke(
        self,
        request: _extension_rpc_pb2.InvokeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_extension_rpc_pb2.InvokeResponse, _abc.Awaitable[_extension_rpc_pb2.InvokeResponse]]:
        """Unary: one request, one response."""

    @_abc_1.abstractmethod
    def ServerStream(
        self,
        request: _extension_rpc_pb2.InvokeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_extension_rpc_pb2.InvokeResponse], _abc.AsyncIterator[_extension_rpc_pb2.InvokeResponse]]:
        """Server-streaming: one request, a stream of responses (status feeds,
        event subscriptions).
        """

def add_ExtensionRpcServicer_to_server(servicer: ExtensionRpcServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
