# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ListExtensionsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListExtensionsRequest: _TypeAlias = ListExtensionsRequest  # noqa: Y015

@_typing.final
class ListExtensionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXTENSIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def extensions(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExtensionInfo]: ...
    def __init__(
        self,
        *,
        extensions: _abc.Iterable[Global___ExtensionInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extensions", b"extensions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListExtensionsResponse: _TypeAlias = ListExtensionsResponse  # noqa: Y015

@_typing.final
class ExtensionInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ConfigEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    ATTACHES_TO_FIELD_NUMBER: _builtins.int
    PROVIDES_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    HAS_UI_FIELD_NUMBER: _builtins.int
    STORAGE_DEVICES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """extension type (from manifest)"""
    id: _builtins.str
    """instance identity (UUID or user-provided)"""
    label: _builtins.str
    """display name (falls back to id)"""
    description: _builtins.str
    """from manifest"""
    has_ui: _builtins.bool
    """True when the extension implements ExtensionUi (i.e. Extension::ui()
    returns non-null). Frontends use this to decide which extensions are
    worth opening an ExtensionUiService.SubscribeView stream to; ones
    without a UI would just return NOT_FOUND.
    """
    @_builtins.property
    def attaches_to(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def provides(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def config(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """current instance configuration"""

    @_builtins.property
    def parameters(self) -> _containers.RepeatedCompositeFieldContainer[Global___ParameterSchemaInfo]:
        """from manifest schema"""

    @_builtins.property
    def storage_devices(self) -> _containers.RepeatedCompositeFieldContainer[Global___StorageDevice]:
        """Storage devices published by this extension (typically empty;
        populated when the extension implements ExtensionStorage on the
        server). One extension can publish multiple devices -- e.g. a
        future Opus Challenger would expose its floppy drive and RAM
        disc as two entries here.
        """

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        id: _builtins.str = ...,
        label: _builtins.str = ...,
        attaches_to: _abc.Iterable[_builtins.str] | None = ...,
        provides: _abc.Iterable[_builtins.str] | None = ...,
        config: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        parameters: _abc.Iterable[Global___ParameterSchemaInfo] | None = ...,
        description: _builtins.str = ...,
        has_ui: _builtins.bool = ...,
        storage_devices: _abc.Iterable[Global___StorageDevice] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attaches_to", b"attaches_to", "config", b"config", "description", b"description", "has_ui", b"has_ui", "id", b"id", "label", b"label", "name", b"name", "parameters", b"parameters", "provides", b"provides", "storage_devices", b"storage_devices"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExtensionInfo: _TypeAlias = ExtensionInfo  # noqa: Y015

@_typing.final
class StorageDevice(_message.Message):
    """A storage device published by a peripheral extension. Surfaced in
    the macOS Storage sidebar (and equivalents elsewhere) below the
    machine's built-in floppy drives. Activity LEDs continue to flow
    through IndicatorService; this message just names the indicator so
    the frontend knows which one to subscribe to.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Kind:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _KindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StorageDevice._Kind.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        FIXED: StorageDevice._Kind.ValueType  # 0
        """Non-removable media: no eject affordance, no path editing.
        Hard discs, RAM discs, anything soldered or fitted in a way
        that doesn't allow runtime swap.
        """
        REMOVABLE: StorageDevice._Kind.ValueType  # 1
        """User-swappable media: future UIs will expose mount, eject,
        and (when empty) a drop / browse target. Not exercised yet.
        """

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    FIXED: StorageDevice.Kind.ValueType  # 0
    """Non-removable media: no eject affordance, no path editing.
    Hard discs, RAM discs, anything soldered or fitted in a way
    that doesn't allow runtime swap.
    """
    REMOVABLE: StorageDevice.Kind.ValueType  # 1
    """User-swappable media: future UIs will expose mount, eject,
    and (when empty) a drop / browse target. Not exercised yet.
    """

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    MEDIA_TYPE_FIELD_NUMBER: _builtins.int
    BACKING_PATH_FIELD_NUMBER: _builtins.int
    ACTIVITY_INDICATOR_NAME_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Stable identifier unique within the process. Conventionally the
    owning extension's id, optionally suffixed when one extension
    publishes multiple devices (e.g. "opus-challenger/ramdisc").
    """
    name: _builtins.str
    """Name of the device in storage-context terms, e.g. "Hard Disc
    Drive 0", "Floppy Disc Drive 1". The numbering convention is
    the device's natural number in its bus / drive-bay scheme
    (SCSI ID for hard discs, drive number for floppies, etc.) so
    it stays stable across reconfigurations and matches related
    labels elsewhere (the "HDD N" entries in the status bar, the
    hdd-N-activity-led indicator names). Distinct from the owning
    extension's label, which may be richer ("Hard Disc (SCSI ID
    0)") -- that label belongs in the Peripherals sidebar where
    SCSI-ID context matters; this name belongs in the Storage
    sidebar where the device-class naming is the right register.
    """
    kind: Global___StorageDevice.Kind.ValueType
    media_type: _builtins.str
    """Semantic media class: "hard-disc", "floppy", "ram-disc",
    "microdrive", etc. Frontends may use this for grouping or
    iconography but should not parse it for behaviour -- the
    kind field carries the behavioural distinction.
    """
    backing_path: _builtins.str
    """Filesystem path to the backing store on the host. For FIXED
    devices this is the always-present image file. For REMOVABLE
    devices it is the currently-mounted image, or empty when no
    media is inserted.
    """
    activity_indicator_name: _builtins.str
    """Name of the per-device activity indicator in IndicatorService,
    e.g. "hdd-0-activity-led" or "floppy-0-activity-led". The
    frontend subscribes to that indicator to drive the row's
    activity dot. Empty when the device has no activity LED.
    """
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        kind: Global___StorageDevice.Kind.ValueType = ...,
        media_type: _builtins.str = ...,
        backing_path: _builtins.str = ...,
        activity_indicator_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activity_indicator_name", b"activity_indicator_name", "backing_path", b"backing_path", "id", b"id", "kind", b"kind", "media_type", b"media_type", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StorageDevice: _TypeAlias = StorageDevice  # noqa: Y015

@_typing.final
class ParameterSchemaInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    POSITION_FIELD_NUMBER: _builtins.int
    REQUIRED_FIELD_NUMBER: _builtins.int
    DEFAULT_VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    type: _builtins.str
    """"string", "integer", "boolean", "filepath" """
    description: _builtins.str
    position: _builtins.int
    """-1 = keyword-only"""
    required: _builtins.bool
    default_value: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        type: _builtins.str = ...,
        description: _builtins.str = ...,
        position: _builtins.int = ...,
        required: _builtins.bool = ...,
        default_value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["default_value", b"default_value", "description", b"description", "key", b"key", "position", b"position", "required", b"required", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ParameterSchemaInfo: _TypeAlias = ParameterSchemaInfo  # noqa: Y015