# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
from . import peripheral_extension_pb2 as _peripheral_extension_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class PeripheralExtensionServiceStub:
    """Service for discovering loaded peripheral extensions.
    This is a core service (always present), not an extension-provided service.
    Frontends use it to enumerate what extensions are loaded and what they provide.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> PeripheralExtensionServiceAsyncStub: ...
    ListExtensions: _grpc.UnaryUnaryMultiCallable[_peripheral_extension_pb2.ListExtensionsRequest, _peripheral_extension_pb2.ListExtensionsResponse]
    """List all loaded and initialised extensions."""

@_typing.type_check_only
class PeripheralExtensionServiceAsyncStub(PeripheralExtensionServiceStub):
    """Service for discovering loaded peripheral extensions.
    This is a core service (always present), not an extension-provided service.
    Frontends use it to enumerate what extensions are loaded and what they provide.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    ListExtensions: _aio.UnaryUnaryMultiCallable[_peripheral_extension_pb2.ListExtensionsRequest, _peripheral_extension_pb2.ListExtensionsResponse]  # type: ignore[assignment]
    """List all loaded and initialised extensions."""

class PeripheralExtensionServiceServicer(metaclass=_abc_1.ABCMeta):
    """Service for discovering loaded peripheral extensions.
    This is a core service (always present), not an extension-provided service.
    Frontends use it to enumerate what extensions are loaded and what they provide.
    """

    @_abc_1.abstractmethod
    def ListExtensions(
        self,
        request: _peripheral_extension_pb2.ListExtensionsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_peripheral_extension_pb2.ListExtensionsResponse, _abc.Awaitable[_peripheral_extension_pb2.ListExtensionsResponse]]:
        """List all loaded and initialised extensions."""

def add_PeripheralExtensionServiceServicer_to_server(servicer: PeripheralExtensionServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...