# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetSerialStatusRequest(_message.Message):
    """Empty - returns full status."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSerialStatusRequest: _TypeAlias = GetSerialStatusRequest  # noqa: Y015

@_typing.final
class WatchSerialStatusRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MIN_INTERVAL_MS_FIELD_NUMBER: _builtins.int
    min_interval_ms: _builtins.int
    """Minimum interval between change checks, in milliseconds (0 = default 50)."""
    def __init__(
        self,
        *,
        min_interval_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["min_interval_ms", b"min_interval_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchSerialStatusRequest: _TypeAlias = WatchSerialStatusRequest  # noqa: Y015

@_typing.final
class SerialStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HAS_SERIAL_SOCKET_FIELD_NUMBER: _builtins.int
    CONNECTOR_FIELD_NUMBER: _builtins.int
    ACIA_CONTROL_FIELD_NUMBER: _builtins.int
    ACIA_STATUS_FIELD_NUMBER: _builtins.int
    TDRE_FIELD_NUMBER: _builtins.int
    RDRF_FIELD_NUMBER: _builtins.int
    NOT_DCD_FIELD_NUMBER: _builtins.int
    NOT_CTS_FIELD_NUMBER: _builtins.int
    IRQ_PENDING_FIELD_NUMBER: _builtins.int
    ULA_CONTROL_FIELD_NUMBER: _builtins.int
    TX_BAUD_FIELD_NUMBER: _builtins.int
    RX_BAUD_FIELD_NUMBER: _builtins.int
    RS423_SELECTED_FIELD_NUMBER: _builtins.int
    MOTOR_ON_FIELD_NUMBER: _builtins.int
    TX_BIT_PERIOD_FIELD_NUMBER: _builtins.int
    RX_BIT_PERIOD_FIELD_NUMBER: _builtins.int
    has_serial_socket: _builtins.bool
    """True if this machine variant has the on-board serial socket."""
    connector: _builtins.str
    """Static, machine-defined: the physical connector standard. "RS423" on the
    Model B / B+ / Master 128; "RS232" on a Master Compact fitted with serial
    (only the signal levels differ -- this is purely a label). Empty when the
    machine has no serial socket.
    """
    acia_control: _builtins.int
    """MC6850 ACIA state.
    last control-register value written
    """
    acia_status: _builtins.int
    """current status-register value"""
    tdre: _builtins.bool
    """Transmit Data Register Empty"""
    rdrf: _builtins.bool
    """Receive Data Register Full"""
    not_dcd: _builtins.bool
    """/DCD pin (true = no carrier)"""
    not_cts: _builtins.bool
    """/CTS pin (true = not clear to send)"""
    irq_pending: _builtins.bool
    """ACIA interrupt output"""
    ula_control: _builtins.int
    """Serial ULA (SERPROC) state.
    last latch value written
    """
    tx_baud: _builtins.int
    """decoded transmit baud rate"""
    rx_baud: _builtins.int
    """decoded receive baud rate"""
    rs423_selected: _builtins.bool
    """RS423 (true) vs cassette (false)"""
    motor_on: _builtins.bool
    """cassette motor relay"""
    tx_bit_period: _builtins.int
    """transmit bit period in 2MHz cycles"""
    rx_bit_period: _builtins.int
    """receive bit period in 2MHz cycles"""
    def __init__(
        self,
        *,
        has_serial_socket: _builtins.bool = ...,
        connector: _builtins.str = ...,
        acia_control: _builtins.int = ...,
        acia_status: _builtins.int = ...,
        tdre: _builtins.bool = ...,
        rdrf: _builtins.bool = ...,
        not_dcd: _builtins.bool = ...,
        not_cts: _builtins.bool = ...,
        irq_pending: _builtins.bool = ...,
        ula_control: _builtins.int = ...,
        tx_baud: _builtins.int = ...,
        rx_baud: _builtins.int = ...,
        rs423_selected: _builtins.bool = ...,
        motor_on: _builtins.bool = ...,
        tx_bit_period: _builtins.int = ...,
        rx_bit_period: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acia_control", b"acia_control", "acia_status", b"acia_status", "connector", b"connector", "has_serial_socket", b"has_serial_socket", "irq_pending", b"irq_pending", "motor_on", b"motor_on", "not_cts", b"not_cts", "not_dcd", b"not_dcd", "rdrf", b"rdrf", "rs423_selected", b"rs423_selected", "rx_baud", b"rx_baud", "rx_bit_period", b"rx_bit_period", "tdre", b"tdre", "tx_baud", b"tx_baud", "tx_bit_period", b"tx_bit_period", "ula_control", b"ula_control"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SerialStatus: _TypeAlias = SerialStatus  # noqa: Y015