# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
from . import serial_pb2 as _serial_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class SerialServiceStub:
    """Serial port (MC6850 ACIA + Serial ULA) status service.

    Reports the live state of the on-board serial hardware. What is attached to
    the far end of the wire is owned by a serial PeripheralExtension (host-serial,
    rpc-serial, loopback-serial, ...), not by this service.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> SerialServiceAsyncStub: ...
    GetSerialStatus: _grpc.UnaryUnaryMultiCallable[_serial_pb2.GetSerialStatusRequest, _serial_pb2.SerialStatus]
    """Query serial hardware status (ACIA + Serial ULA registers)."""
    WatchSerialStatus: _grpc.UnaryStreamMultiCallable[_serial_pb2.WatchSerialStatusRequest, _serial_pb2.SerialStatus]
    """Server-pushed status stream. Writes an initial SerialStatus as soon as the
    stream is established, then a fresh snapshot whenever the chip state
    changes (sampled at min_interval_ms, so rapid TDRE/RDRF toggling during a
    transfer is coalesced). The stream stays open until the client cancels;
    use this instead of polling GetSerialStatus.
    """

@_typing.type_check_only
class SerialServiceAsyncStub(SerialServiceStub):
    """Serial port (MC6850 ACIA + Serial ULA) status service.

    Reports the live state of the on-board serial hardware. What is attached to
    the far end of the wire is owned by a serial PeripheralExtension (host-serial,
    rpc-serial, loopback-serial, ...), not by this service.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetSerialStatus: _aio.UnaryUnaryMultiCallable[_serial_pb2.GetSerialStatusRequest, _serial_pb2.SerialStatus]  # type: ignore[assignment]
    """Query serial hardware status (ACIA + Serial ULA registers)."""
    WatchSerialStatus: _aio.UnaryStreamMultiCallable[_serial_pb2.WatchSerialStatusRequest, _serial_pb2.SerialStatus]  # type: ignore[assignment]
    """Server-pushed status stream. Writes an initial SerialStatus as soon as the
    stream is established, then a fresh snapshot whenever the chip state
    changes (sampled at min_interval_ms, so rapid TDRE/RDRF toggling during a
    transfer is coalesced). The stream stays open until the client cancels;
    use this instead of polling GetSerialStatus.
    """

class SerialServiceServicer(metaclass=_abc_1.ABCMeta):
    """Serial port (MC6850 ACIA + Serial ULA) status service.

    Reports the live state of the on-board serial hardware. What is attached to
    the far end of the wire is owned by a serial PeripheralExtension (host-serial,
    rpc-serial, loopback-serial, ...), not by this service.
    """

    @_abc_1.abstractmethod
    def GetSerialStatus(
        self,
        request: _serial_pb2.GetSerialStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_serial_pb2.SerialStatus, _abc.Awaitable[_serial_pb2.SerialStatus]]:
        """Query serial hardware status (ACIA + Serial ULA registers)."""

    @_abc_1.abstractmethod
    def WatchSerialStatus(
        self,
        request: _serial_pb2.WatchSerialStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_serial_pb2.SerialStatus], _abc.AsyncIterator[_serial_pb2.SerialStatus]]:
        """Server-pushed status stream. Writes an initial SerialStatus as soon as the
        stream is established, then a fresh snapshot whenever the chip state
        changes (sampled at min_interval_ms, so rapid TDRE/RDRF toggling during a
        transfer is coalesced). The stream stays open until the client cancels;
        use this instead of polling GetSerialStatus.
        """

def add_SerialServiceServicer_to_server(servicer: SerialServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...