# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _FieldOrder:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FieldOrderEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FieldOrder.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PROGRESSIVE: _FieldOrder.ValueType  # 0
    """Non-interlaced, single pass"""
    EVEN_FIRST: _FieldOrder.ValueType  # 1
    """Even lines (0,2,4...) rendered first temporally"""
    ODD_FIRST: _FieldOrder.ValueType  # 2
    """Odd lines (1,3,5...) rendered first temporally"""

class FieldOrder(_FieldOrder, metaclass=_FieldOrderEnumTypeWrapper):
    """Field ordering for interlaced frames.
    Clients can split composited frames into fields for authentic 50Hz display.
    """

PROGRESSIVE: FieldOrder.ValueType  # 0
"""Non-interlaced, single pass"""
EVEN_FIRST: FieldOrder.ValueType  # 1
"""Even lines (0,2,4...) rendered first temporally"""
ODD_FIRST: FieldOrder.ValueType  # 2
"""Odd lines (1,3,5...) rendered first temporally"""
Global___FieldOrder: _TypeAlias = FieldOrder  # noqa: Y015

@_typing.final
class SubscribeFramesRequest(_message.Message):
    """Future: format preferences, scaling options"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubscribeFramesRequest: _TypeAlias = SubscribeFramesRequest  # noqa: Y015

@_typing.final
class Frame(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FRAME_NUMBER_FIELD_NUMBER: _builtins.int
    CYCLE_COUNT_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    PIXELS_FIELD_NUMBER: _builtins.int
    FIELD_ORDER_FIELD_NUMBER: _builtins.int
    LEFT_BORDER_FIELD_NUMBER: _builtins.int
    RIGHT_BORDER_FIELD_NUMBER: _builtins.int
    TOP_BORDER_FIELD_NUMBER: _builtins.int
    BOTTOM_BORDER_FIELD_NUMBER: _builtins.int
    DISPLAY_WIDTH_FIELD_NUMBER: _builtins.int
    DISPLAY_HEIGHT_FIELD_NUMBER: _builtins.int
    REGIONS_FIELD_NUMBER: _builtins.int
    frame_number: _builtins.int
    cycle_count: _builtins.int
    width: _builtins.int
    """Logical width in pixels (varies by mode)"""
    height: _builtins.int
    """Logical height in scanlines"""
    pixels: _builtins.bytes
    """BGRA32 pixel data, width * height * 4 bytes"""
    field_order: Global___FieldOrder.ValueType
    """For interlaced modes (e.g., MODE 7)"""
    left_border: _builtins.int
    """Border dimensions (pixels/scanlines of blanking around active area)
    Clients can use these for authentic CRT-style display with borders.
    Add left_border + width + right_border for total horizontal extent.
    Pixels from left edge to active area
    """
    right_border: _builtins.int
    """Pixels from active area to right edge"""
    top_border: _builtins.int
    """Scanlines from top edge to active area"""
    bottom_border: _builtins.int
    """Scanlines from active area to bottom edge"""
    display_width: _builtins.int
    """Target display resolution for scaling.
    BBC Micro displays all modes at the same physical CRT size.
    Clients should scale: width -> display_width, height -> display_height
    Examples:
      MODE 0: 640x256 logical = 640x256 display (1:1)
      MODE 1: 320x256 logical = 640x256 display (2:1 horizontal)
      MODE 2: 160x256 logical = 640x256 display (4:1 horizontal)
    Target display width (typically 640)
    """
    display_height: _builtins.int
    """Target display height (typically 256)"""
    @_builtins.property
    def regions(self) -> _containers.RepeatedCompositeFieldContainer[Global___DisplayRegion]:
        """Per-region display geometry for split-screen modes.
        Always populated with at least one region.
        """

    def __init__(
        self,
        *,
        frame_number: _builtins.int = ...,
        cycle_count: _builtins.int = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
        pixels: _builtins.bytes = ...,
        field_order: Global___FieldOrder.ValueType = ...,
        left_border: _builtins.int = ...,
        right_border: _builtins.int = ...,
        top_border: _builtins.int = ...,
        bottom_border: _builtins.int = ...,
        display_width: _builtins.int = ...,
        display_height: _builtins.int = ...,
        regions: _abc.Iterable[Global___DisplayRegion] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bottom_border", b"bottom_border", "cycle_count", b"cycle_count", "display_height", b"display_height", "display_width", b"display_width", "field_order", b"field_order", "frame_number", b"frame_number", "height", b"height", "left_border", b"left_border", "pixels", b"pixels", "regions", b"regions", "right_border", b"right_border", "top_border", b"top_border", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Frame: _TypeAlias = Frame  # noqa: Y015

@_typing.final
class DisplayRegion(_message.Message):
    """A horizontal region of scanlines sharing the same logical pixel width.
    Used for split-screen modes where the CRTC is reprogrammed mid-frame
    (e.g., Elite uses MODE 4 upper / MODE 5 lower).
    """

    DESCRIPTOR: _descriptor.Descriptor

    START_LINE_FIELD_NUMBER: _builtins.int
    END_LINE_FIELD_NUMBER: _builtins.int
    PIXEL_WIDTH_FIELD_NUMBER: _builtins.int
    start_line: _builtins.int
    """First scanline (inclusive, 0-based)"""
    end_line: _builtins.int
    """Last scanline (exclusive)"""
    pixel_width: _builtins.int
    """Logical pixel width for scanlines in this region"""
    def __init__(
        self,
        *,
        start_line: _builtins.int = ...,
        end_line: _builtins.int = ...,
        pixel_width: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end_line", b"end_line", "pixel_width", b"pixel_width", "start_line", b"start_line"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DisplayRegion: _TypeAlias = DisplayRegion  # noqa: Y015

@_typing.final
class GetConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetConfigRequest: _TypeAlias = GetConfigRequest  # noqa: Y015

@_typing.final
class VideoConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    FRAMERATE_HZ_FIELD_NUMBER: _builtins.int
    width: _builtins.int
    """640 for Mode 0-6, 480 for Mode 7"""
    height: _builtins.int
    """256 typical"""
    framerate_hz: _builtins.int
    """50Hz PAL"""
    def __init__(
        self,
        *,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
        framerate_hz: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["framerate_hz", b"framerate_hz", "height", b"height", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VideoConfig: _TypeAlias = VideoConfig  # noqa: Y015