# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import peripheral_extension_pb2 as peripheral__extension__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in peripheral_extension_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeripheralExtensionServiceStub(object):
    """Service for discovering loaded peripheral extensions.
    This is a core service (always present), not an extension-provided service.
    Frontends use it to enumerate what extensions are loaded and what they provide.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListExtensions = channel.unary_unary(
                '/beebium.PeripheralExtensionService/ListExtensions',
                request_serializer=peripheral__extension__pb2.ListExtensionsRequest.SerializeToString,
                response_deserializer=peripheral__extension__pb2.ListExtensionsResponse.FromString,
                _registered_method=True)


class PeripheralExtensionServiceServicer(object):
    """Service for discovering loaded peripheral extensions.
    This is a core service (always present), not an extension-provided service.
    Frontends use it to enumerate what extensions are loaded and what they provide.
    """

    def ListExtensions(self, request, context):
        """List all loaded and initialised extensions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeripheralExtensionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListExtensions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExtensions,
                    request_deserializer=peripheral__extension__pb2.ListExtensionsRequest.FromString,
                    response_serializer=peripheral__extension__pb2.ListExtensionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.PeripheralExtensionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.PeripheralExtensionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeripheralExtensionService(object):
    """Service for discovering loaded peripheral extensions.
    This is a core service (always present), not an extension-provided service.
    Frontends use it to enumerate what extensions are loaded and what they provide.
    """

    @staticmethod
    def ListExtensions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.PeripheralExtensionService/ListExtensions',
            peripheral__extension__pb2.ListExtensionsRequest.SerializeToString,
            peripheral__extension__pb2.ListExtensionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)