# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
from . import scsi_host_adapter_pb2 as _scsi_host_adapter_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ScsiHostAdapterServiceStub:
    """Service for managing the Acorn SCSI host adapter and its attached targets."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ScsiHostAdapterServiceAsyncStub: ...
    ListTargets: _grpc.UnaryUnaryMultiCallable[_scsi_host_adapter_pb2.ListScsiTargetsRequest, _scsi_host_adapter_pb2.ListScsiTargetsResponse]
    """List all SCSI targets (installed devices on the bus)."""
    GetBusStatus: _grpc.UnaryUnaryMultiCallable[_scsi_host_adapter_pb2.GetScsiBusStatusRequest, _scsi_host_adapter_pb2.GetScsiBusStatusResponse]
    """Query the current SCSI bus state."""
    WatchBusEvents: _grpc.UnaryStreamMultiCallable[_scsi_host_adapter_pb2.WatchScsiBusEventsRequest, _scsi_host_adapter_pb2.ScsiBusEvent]
    """Stream SCSI bus events in real-time. Events are emitted for phase
    transitions, commands dispatched, data transfers, and completion.
    The stream continues until the client disconnects.
    """

@_typing.type_check_only
class ScsiHostAdapterServiceAsyncStub(ScsiHostAdapterServiceStub):
    """Service for managing the Acorn SCSI host adapter and its attached targets."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    ListTargets: _aio.UnaryUnaryMultiCallable[_scsi_host_adapter_pb2.ListScsiTargetsRequest, _scsi_host_adapter_pb2.ListScsiTargetsResponse]  # type: ignore[assignment]
    """List all SCSI targets (installed devices on the bus)."""
    GetBusStatus: _aio.UnaryUnaryMultiCallable[_scsi_host_adapter_pb2.GetScsiBusStatusRequest, _scsi_host_adapter_pb2.GetScsiBusStatusResponse]  # type: ignore[assignment]
    """Query the current SCSI bus state."""
    WatchBusEvents: _aio.UnaryStreamMultiCallable[_scsi_host_adapter_pb2.WatchScsiBusEventsRequest, _scsi_host_adapter_pb2.ScsiBusEvent]  # type: ignore[assignment]
    """Stream SCSI bus events in real-time. Events are emitted for phase
    transitions, commands dispatched, data transfers, and completion.
    The stream continues until the client disconnects.
    """

class ScsiHostAdapterServiceServicer(metaclass=_abc_1.ABCMeta):
    """Service for managing the Acorn SCSI host adapter and its attached targets."""

    @_abc_1.abstractmethod
    def ListTargets(
        self,
        request: _scsi_host_adapter_pb2.ListScsiTargetsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_scsi_host_adapter_pb2.ListScsiTargetsResponse, _abc.Awaitable[_scsi_host_adapter_pb2.ListScsiTargetsResponse]]:
        """List all SCSI targets (installed devices on the bus)."""

    @_abc_1.abstractmethod
    def GetBusStatus(
        self,
        request: _scsi_host_adapter_pb2.GetScsiBusStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_scsi_host_adapter_pb2.GetScsiBusStatusResponse, _abc.Awaitable[_scsi_host_adapter_pb2.GetScsiBusStatusResponse]]:
        """Query the current SCSI bus state."""

    @_abc_1.abstractmethod
    def WatchBusEvents(
        self,
        request: _scsi_host_adapter_pb2.WatchScsiBusEventsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_scsi_host_adapter_pb2.ScsiBusEvent], _abc.AsyncIterator[_scsi_host_adapter_pb2.ScsiBusEvent]]:
        """Stream SCSI bus events in real-time. Events are emitted for phase
        transitions, commands dispatched, data transfers, and completion.
        The stream continues until the client disconnects.
        """

def add_ScsiHostAdapterServiceServicer_to_server(servicer: ScsiHostAdapterServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...