# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ListScsiTargetsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListScsiTargetsRequest: _TypeAlias = ListScsiTargetsRequest  # noqa: Y015

@_typing.final
class ListScsiTargetsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TARGETS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def targets(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScsiTargetInfo]: ...
    def __init__(
        self,
        *,
        targets: _abc.Iterable[Global___ScsiTargetInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["targets", b"targets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListScsiTargetsResponse: _TypeAlias = ListScsiTargetsResponse  # noqa: Y015

@_typing.final
class ScsiTargetInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    PRESENT_FIELD_NUMBER: _builtins.int
    DEVICE_TYPE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    """SCSI ID 0-7"""
    present: _builtins.bool
    """target responding on the bus"""
    device_type: _builtins.str
    """e.g. "hard-disc", "test-device", "vp415" """
    description: _builtins.str
    """human-readable description"""
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        present: _builtins.bool = ...,
        device_type: _builtins.str = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "device_type", b"device_type", "id", b"id", "present", b"present"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScsiTargetInfo: _TypeAlias = ScsiTargetInfo  # noqa: Y015

@_typing.final
class GetScsiBusStatusRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetScsiBusStatusRequest: _TypeAlias = GetScsiBusStatusRequest  # noqa: Y015

@_typing.final
class GetScsiBusStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PHASE_FIELD_NUMBER: _builtins.int
    SELECTED_TARGET_FIELD_NUMBER: _builtins.int
    STATUS_REGISTER_FIELD_NUMBER: _builtins.int
    IRQ_PENDING_FIELD_NUMBER: _builtins.int
    phase: _builtins.str
    """e.g. "BUS_FREE", "COMMAND", "DATA_IN" """
    selected_target: _builtins.int
    """0xFF if none selected"""
    status_register: _builtins.int
    """raw status register byte"""
    irq_pending: _builtins.bool
    def __init__(
        self,
        *,
        phase: _builtins.str = ...,
        selected_target: _builtins.int = ...,
        status_register: _builtins.int = ...,
        irq_pending: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["irq_pending", b"irq_pending", "phase", b"phase", "selected_target", b"selected_target", "status_register", b"status_register"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetScsiBusStatusResponse: _TypeAlias = GetScsiBusStatusResponse  # noqa: Y015

@_typing.final
class WatchScsiBusEventsRequest(_message.Message):
    """Request to start watching SCSI bus events."""

    DESCRIPTOR: _descriptor.Descriptor

    INCLUDE_REGISTER_ACCESS_FIELD_NUMBER: _builtins.int
    include_register_access: _builtins.bool
    """If true, include register-level reads/writes (verbose).
    If false, only include command-level events.
    """
    def __init__(
        self,
        *,
        include_register_access: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["include_register_access", b"include_register_access"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchScsiBusEventsRequest: _TypeAlias = WatchScsiBusEventsRequest  # noqa: Y015

@_typing.final
class ScsiBusEvent(_message.Message):
    """A single SCSI bus event."""

    DESCRIPTOR: _descriptor.Descriptor

    CYCLE_COUNT_FIELD_NUMBER: _builtins.int
    PHASE_CHANGE_FIELD_NUMBER: _builtins.int
    COMMAND_FIELD_NUMBER: _builtins.int
    DATA_TRANSFER_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REGISTER_ACCESS_FIELD_NUMBER: _builtins.int
    SELECTION_FIELD_NUMBER: _builtins.int
    cycle_count: _builtins.int
    """emulated cycle count when the event occurred"""
    @_builtins.property
    def phase_change(self) -> Global___PhaseChangeEvent: ...
    @_builtins.property
    def command(self) -> Global___CommandEvent: ...
    @_builtins.property
    def data_transfer(self) -> Global___DataTransferEvent: ...
    @_builtins.property
    def status(self) -> Global___StatusEvent: ...
    @_builtins.property
    def register_access(self) -> Global___RegisterAccessEvent: ...
    @_builtins.property
    def selection(self) -> Global___SelectionEvent: ...
    def __init__(
        self,
        *,
        cycle_count: _builtins.int = ...,
        phase_change: Global___PhaseChangeEvent | None = ...,
        command: Global___CommandEvent | None = ...,
        data_transfer: Global___DataTransferEvent | None = ...,
        status: Global___StatusEvent | None = ...,
        register_access: Global___RegisterAccessEvent | None = ...,
        selection: Global___SelectionEvent | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "data_transfer", b"data_transfer", "event", b"event", "phase_change", b"phase_change", "register_access", b"register_access", "selection", b"selection", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "cycle_count", b"cycle_count", "data_transfer", b"data_transfer", "event", b"event", "phase_change", b"phase_change", "register_access", b"register_access", "selection", b"selection", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["phase_change", "command", "data_transfer", "status", "register_access", "selection"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___ScsiBusEvent: _TypeAlias = ScsiBusEvent  # noqa: Y015

@_typing.final
class PhaseChangeEvent(_message.Message):
    """The bus transitioned to a new phase."""

    DESCRIPTOR: _descriptor.Descriptor

    FROM_PHASE_FIELD_NUMBER: _builtins.int
    TO_PHASE_FIELD_NUMBER: _builtins.int
    from_phase: _builtins.str
    """e.g. "COMMAND" """
    to_phase: _builtins.str
    """e.g. "DATA_OUT" """
    def __init__(
        self,
        *,
        from_phase: _builtins.str = ...,
        to_phase: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["from_phase", b"from_phase", "to_phase", b"to_phase"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PhaseChangeEvent: _TypeAlias = PhaseChangeEvent  # noqa: Y015

@_typing.final
class CommandEvent(_message.Message):
    """A complete SCSI command was dispatched to a target."""

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_ID_FIELD_NUMBER: _builtins.int
    OPCODE_FIELD_NUMBER: _builtins.int
    OPCODE_NAME_FIELD_NUMBER: _builtins.int
    CDB_FIELD_NUMBER: _builtins.int
    LBA_FIELD_NUMBER: _builtins.int
    BLOCK_COUNT_FIELD_NUMBER: _builtins.int
    target_id: _builtins.int
    """SCSI target that received the command"""
    opcode: _builtins.int
    """SCSI opcode (e.g. 0x08 = READ(6), 0x0A = WRITE(6))"""
    opcode_name: _builtins.str
    """human-readable name (e.g. "WRITE(6)")"""
    cdb: _builtins.bytes
    """complete Command Descriptor Block"""
    lba: _builtins.int
    """logical block address (decoded from CDB)"""
    block_count: _builtins.int
    """number of blocks (decoded from CDB)"""
    def __init__(
        self,
        *,
        target_id: _builtins.int = ...,
        opcode: _builtins.int = ...,
        opcode_name: _builtins.str = ...,
        cdb: _builtins.bytes = ...,
        lba: _builtins.int = ...,
        block_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block_count", b"block_count", "cdb", b"cdb", "lba", b"lba", "opcode", b"opcode", "opcode_name", b"opcode_name", "target_id", b"target_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CommandEvent: _TypeAlias = CommandEvent  # noqa: Y015

@_typing.final
class DataTransferEvent(_message.Message):
    """A data transfer phase completed (or is in progress)."""

    DESCRIPTOR: _descriptor.Descriptor

    DIRECTION_FIELD_NUMBER: _builtins.int
    BYTES_EXPECTED_FIELD_NUMBER: _builtins.int
    BYTES_TRANSFERRED_FIELD_NUMBER: _builtins.int
    COMPLETE_FIELD_NUMBER: _builtins.int
    direction: _builtins.str
    """"IN" (target->host) or "OUT" (host->target)"""
    bytes_expected: _builtins.int
    """total bytes expected for this transfer"""
    bytes_transferred: _builtins.int
    """bytes transferred so far"""
    complete: _builtins.bool
    """true when transfer is complete"""
    def __init__(
        self,
        *,
        direction: _builtins.str = ...,
        bytes_expected: _builtins.int = ...,
        bytes_transferred: _builtins.int = ...,
        complete: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bytes_expected", b"bytes_expected", "bytes_transferred", b"bytes_transferred", "complete", b"complete", "direction", b"direction"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DataTransferEvent: _TypeAlias = DataTransferEvent  # noqa: Y015

@_typing.final
class StatusEvent(_message.Message):
    """Command completed with a status byte."""

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_ID_FIELD_NUMBER: _builtins.int
    STATUS_BYTE_FIELD_NUMBER: _builtins.int
    STATUS_NAME_FIELD_NUMBER: _builtins.int
    MESSAGE_BYTE_FIELD_NUMBER: _builtins.int
    target_id: _builtins.int
    status_byte: _builtins.int
    """0x00 = GOOD, 0x02 = CHECK CONDITION, etc."""
    status_name: _builtins.str
    """human-readable name"""
    message_byte: _builtins.int
    """message byte (typically 0x00 = COMMAND COMPLETE)"""
    def __init__(
        self,
        *,
        target_id: _builtins.int = ...,
        status_byte: _builtins.int = ...,
        status_name: _builtins.str = ...,
        message_byte: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message_byte", b"message_byte", "status_byte", b"status_byte", "status_name", b"status_name", "target_id", b"target_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StatusEvent: _TypeAlias = StatusEvent  # noqa: Y015

@_typing.final
class SelectionEvent(_message.Message):
    """A target was selected on the bus."""

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_ID_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    target_id: _builtins.int
    """selected target ID"""
    success: _builtins.bool
    """true if target responded"""
    def __init__(
        self,
        *,
        target_id: _builtins.int = ...,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success", "target_id", b"target_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SelectionEvent: _TypeAlias = SelectionEvent  # noqa: Y015

@_typing.final
class RegisterAccessEvent(_message.Message):
    """A register read or write (verbose, only if requested)."""

    DESCRIPTOR: _descriptor.Descriptor

    OPERATION_FIELD_NUMBER: _builtins.int
    REGISTER_INDEX_FIELD_NUMBER: _builtins.int
    REGISTER_NAME_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    PHASE_FIELD_NUMBER: _builtins.int
    operation: _builtins.str
    """"READ" or "WRITE" """
    register_index: _builtins.int
    """0=data, 1=status, 2=select, 3=irq"""
    register_name: _builtins.str
    """"DATA", "STATUS", "SELECT", "IRQ" """
    value: _builtins.int
    """byte value read/written"""
    phase: _builtins.str
    """current bus phase"""
    def __init__(
        self,
        *,
        operation: _builtins.str = ...,
        register_index: _builtins.int = ...,
        register_name: _builtins.str = ...,
        value: _builtins.int = ...,
        phase: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["operation", b"operation", "phase", b"phase", "register_index", b"register_index", "register_name", b"register_name", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterAccessEvent: _TypeAlias = RegisterAccessEvent  # noqa: Y015