10 *ADFS
20 REM Test sequential file I/O
30 *CDIR TESTIO
40 *DIR TESTIO
50 F%=OPENOUT("SEQ")
60 PRINT#F%,"Alpha"
70 PRINT#F%,"Beta"
80 CLOSE#F%
90 PRINT "TEST:WRITE:PASS"
100 F%=OPENIN("SEQ")
110 INPUT#F%,A$
120 INPUT#F%,B$
130 IF A$="Alpha" AND B$="Beta" THEN PRINT "TEST:READ:PASS" ELSE PRINT "TEST:READ:FAIL"
140 E%=EXT#F%
150 IF E%>0 THEN PRINT "TEST:EXT:PASS" ELSE PRINT "TEST:EXT:FAIL"
160 IF EOF#F% THEN PRINT "TEST:EOF:PASS" ELSE PRINT "TEST:EOF:FAIL"
170 PTR#F%=0
180 INPUT#F%,C$
190 IF C$="Alpha" THEN PRINT "TEST:PTR:PASS" ELSE PRINT "TEST:PTR:FAIL"
200 CLOSE#F%
210 PRINT "DONE"
