# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetRtcTimeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRtcTimeRequest: _TypeAlias = GetRtcTimeRequest  # noqa: Y015

@_typing.final
class GetRtcTimeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    YEAR_FIELD_NUMBER: _builtins.int
    MONTH_FIELD_NUMBER: _builtins.int
    DAY_FIELD_NUMBER: _builtins.int
    HOUR_FIELD_NUMBER: _builtins.int
    MINUTE_FIELD_NUMBER: _builtins.int
    ISO8601_FIELD_NUMBER: _builtins.int
    year: _builtins.int
    """full year (1981 + register 1 offset)"""
    month: _builtins.int
    """1-12"""
    day: _builtins.int
    """1-31"""
    hour: _builtins.int
    """0-23"""
    minute: _builtins.int
    """0-59"""
    iso8601: _builtins.str
    """e.g. "1985-06-15T14:30" """
    def __init__(
        self,
        *,
        year: _builtins.int = ...,
        month: _builtins.int = ...,
        day: _builtins.int = ...,
        hour: _builtins.int = ...,
        minute: _builtins.int = ...,
        iso8601: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["day", b"day", "hour", b"hour", "iso8601", b"iso8601", "minute", b"minute", "month", b"month", "year", b"year"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRtcTimeResponse: _TypeAlias = GetRtcTimeResponse  # noqa: Y015

@_typing.final
class SetRtcTimeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ISO8601_FIELD_NUMBER: _builtins.int
    iso8601: _builtins.str
    """e.g. "1985-06-15T14:30" """
    def __init__(
        self,
        *,
        iso8601: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["iso8601", b"iso8601"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetRtcTimeRequest: _TypeAlias = SetRtcTimeRequest  # noqa: Y015

@_typing.final
class SetRtcTimeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetRtcTimeResponse: _TypeAlias = SetRtcTimeResponse  # noqa: Y015

@_typing.final
class GetRtcRegistersRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRtcRegistersRequest: _TypeAlias = GetRtcRegistersRequest  # noqa: Y015

@_typing.final
class GetRtcRegistersResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGISTERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def registers(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """8 BCD register values in order:
          [0] month counter, [1] month alarm (year), [2] date counter,
          [3] date alarm (old month + leap flag), [4] hours counter,
          [5] hours alarm (unused), [6] minutes counter, [7] minutes alarm (dongle)
        """

    def __init__(
        self,
        *,
        registers: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["registers", b"registers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRtcRegistersResponse: _TypeAlias = GetRtcRegistersResponse  # noqa: Y015

@_typing.final
class SetRtcRegisterRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGISTER_INDEX_FIELD_NUMBER: _builtins.int
    BCD_VALUE_FIELD_NUMBER: _builtins.int
    register_index: _builtins.int
    """0-7"""
    bcd_value: _builtins.int
    """raw BCD byte (wrapping applied by chip)"""
    def __init__(
        self,
        *,
        register_index: _builtins.int = ...,
        bcd_value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bcd_value", b"bcd_value", "register_index", b"register_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetRtcRegisterRequest: _TypeAlias = SetRtcRegisterRequest  # noqa: Y015

@_typing.final
class SetRtcRegisterResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetRtcRegisterResponse: _TypeAlias = SetRtcRegisterResponse  # noqa: Y015

@_typing.final
class WatchActivityRequest(_message.Message):
    """--- Watch Activity ---"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchActivityRequest: _TypeAlias = WatchActivityRequest  # noqa: Y015

@_typing.final
class RtcActivityEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _EventType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EventTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[RtcActivityEvent._EventType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        REGISTER_READ: RtcActivityEvent._EventType.ValueType  # 0
        REGISTER_WRITE: RtcActivityEvent._EventType.ValueType  # 1

    class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper): ...
    REGISTER_READ: RtcActivityEvent.EventType.ValueType  # 0
    REGISTER_WRITE: RtcActivityEvent.EventType.ValueType  # 1

    TYPE_FIELD_NUMBER: _builtins.int
    REGISTER_NUMBER_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_US_FIELD_NUMBER: _builtins.int
    type: Global___RtcActivityEvent.EventType.ValueType
    register_number: _builtins.int
    value: _builtins.int
    """BCD value read or written"""
    timestamp_us: _builtins.int
    """Microseconds since epoch (steady_clock)"""
    def __init__(
        self,
        *,
        type: Global___RtcActivityEvent.EventType.ValueType = ...,
        register_number: _builtins.int = ...,
        value: _builtins.int = ...,
        timestamp_us: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["register_number", b"register_number", "timestamp_us", b"timestamp_us", "type", b"type", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RtcActivityEvent: _TypeAlias = RtcActivityEvent  # noqa: Y015