# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: acorn_rtc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'acorn_rtc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61\x63orn_rtc.proto\x12\x07\x62\x65\x65\x62ium\"\x13\n\x11GetRtcTimeRequest\"m\n\x12GetRtcTimeResponse\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\x12\x0c\n\x04hour\x18\x04 \x01(\x05\x12\x0e\n\x06minute\x18\x05 \x01(\x05\x12\x0f\n\x07iso8601\x18\x06 \x01(\t\"$\n\x11SetRtcTimeRequest\x12\x0f\n\x07iso8601\x18\x01 \x01(\t\"\x14\n\x12SetRtcTimeResponse\"\x18\n\x16GetRtcRegistersRequest\",\n\x17GetRtcRegistersResponse\x12\x11\n\tregisters\x18\x01 \x03(\r\"B\n\x15SetRtcRegisterRequest\x12\x16\n\x0eregister_index\x18\x01 \x01(\r\x12\x11\n\tbcd_value\x18\x02 \x01(\r\"\x18\n\x16SetRtcRegisterResponse\"\x16\n\x14WatchActivityRequest\"\xb7\x01\n\x10RtcActivityEvent\x12\x31\n\x04type\x18\x01 \x01(\x0e\x32#.beebium.RtcActivityEvent.EventType\x12\x17\n\x0fregister_number\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\x12\x14\n\x0ctimestamp_us\x18\x04 \x01(\x03\"2\n\tEventType\x12\x11\n\rREGISTER_READ\x10\x00\x12\x12\n\x0eREGISTER_WRITE\x10\x01\x32\x89\x03\n\x0f\x41\x63ornRtcService\x12\x42\n\x07GetTime\x12\x1a.beebium.GetRtcTimeRequest\x1a\x1b.beebium.GetRtcTimeResponse\x12\x42\n\x07SetTime\x12\x1a.beebium.SetRtcTimeRequest\x1a\x1b.beebium.SetRtcTimeResponse\x12Q\n\x0cGetRegisters\x12\x1f.beebium.GetRtcRegistersRequest\x1a .beebium.GetRtcRegistersResponse\x12N\n\x0bSetRegister\x12\x1e.beebium.SetRtcRegisterRequest\x1a\x1f.beebium.SetRtcRegisterResponse\x12K\n\rWatchActivity\x12\x1d.beebium.WatchActivityRequest\x1a\x19.beebium.RtcActivityEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acorn_rtc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETRTCTIMEREQUEST']._serialized_start=28
  _globals['_GETRTCTIMEREQUEST']._serialized_end=47
  _globals['_GETRTCTIMERESPONSE']._serialized_start=49
  _globals['_GETRTCTIMERESPONSE']._serialized_end=158
  _globals['_SETRTCTIMEREQUEST']._serialized_start=160
  _globals['_SETRTCTIMEREQUEST']._serialized_end=196
  _globals['_SETRTCTIMERESPONSE']._serialized_start=198
  _globals['_SETRTCTIMERESPONSE']._serialized_end=218
  _globals['_GETRTCREGISTERSREQUEST']._serialized_start=220
  _globals['_GETRTCREGISTERSREQUEST']._serialized_end=244
  _globals['_GETRTCREGISTERSRESPONSE']._serialized_start=246
  _globals['_GETRTCREGISTERSRESPONSE']._serialized_end=290
  _globals['_SETRTCREGISTERREQUEST']._serialized_start=292
  _globals['_SETRTCREGISTERREQUEST']._serialized_end=358
  _globals['_SETRTCREGISTERRESPONSE']._serialized_start=360
  _globals['_SETRTCREGISTERRESPONSE']._serialized_end=384
  _globals['_WATCHACTIVITYREQUEST']._serialized_start=386
  _globals['_WATCHACTIVITYREQUEST']._serialized_end=408
  _globals['_RTCACTIVITYEVENT']._serialized_start=411
  _globals['_RTCACTIVITYEVENT']._serialized_end=594
  _globals['_RTCACTIVITYEVENT_EVENTTYPE']._serialized_start=544
  _globals['_RTCACTIVITYEVENT_EVENTTYPE']._serialized_end=594
  _globals['_ACORNRTCSERVICE']._serialized_start=597
  _globals['_ACORNRTCSERVICE']._serialized_end=990
# @@protoc_insertion_point(module_scope)