# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
from . import acorn_rtc_pb2 as _acorn_rtc_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AcornRtcServiceStub:
    """Service for managing the SAF3019P Real Time Clock on the User Port."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AcornRtcServiceAsyncStub: ...
    GetTime: _grpc.UnaryUnaryMultiCallable[_acorn_rtc_pb2.GetRtcTimeRequest, _acorn_rtc_pb2.GetRtcTimeResponse]
    """Read the current emulated date and time (decoded from chip registers)."""
    SetTime: _grpc.UnaryUnaryMultiCallable[_acorn_rtc_pb2.SetRtcTimeRequest, _acorn_rtc_pb2.SetRtcTimeResponse]
    """Set the emulated date and time (writes all chip registers).
    Returns INVALID_ARGUMENT if the year is outside the representable
    range (1981-2000).
    """
    GetRegisters: _grpc.UnaryUnaryMultiCallable[_acorn_rtc_pb2.GetRtcRegistersRequest, _acorn_rtc_pb2.GetRtcRegistersResponse]
    """Read all 8 raw BCD register values."""
    SetRegister: _grpc.UnaryUnaryMultiCallable[_acorn_rtc_pb2.SetRtcRegisterRequest, _acorn_rtc_pb2.SetRtcRegisterResponse]
    """Write a single register with a raw BCD value.
    The chip's per-register wrapping is applied faithfully.
    """
    WatchActivity: _grpc.UnaryStreamMultiCallable[_acorn_rtc_pb2.WatchActivityRequest, _acorn_rtc_pb2.RtcActivityEvent]
    """Stream CBUS activity events (register reads and writes by the BBC).
    Analogous to watching the DATA LED on Ken Lowe's reproduction hardware.
    """

@_typing.type_check_only
class AcornRtcServiceAsyncStub(AcornRtcServiceStub):
    """Service for managing the SAF3019P Real Time Clock on the User Port."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetTime: _aio.UnaryUnaryMultiCallable[_acorn_rtc_pb2.GetRtcTimeRequest, _acorn_rtc_pb2.GetRtcTimeResponse]  # type: ignore[assignment]
    """Read the current emulated date and time (decoded from chip registers)."""
    SetTime: _aio.UnaryUnaryMultiCallable[_acorn_rtc_pb2.SetRtcTimeRequest, _acorn_rtc_pb2.SetRtcTimeResponse]  # type: ignore[assignment]
    """Set the emulated date and time (writes all chip registers).
    Returns INVALID_ARGUMENT if the year is outside the representable
    range (1981-2000).
    """
    GetRegisters: _aio.UnaryUnaryMultiCallable[_acorn_rtc_pb2.GetRtcRegistersRequest, _acorn_rtc_pb2.GetRtcRegistersResponse]  # type: ignore[assignment]
    """Read all 8 raw BCD register values."""
    SetRegister: _aio.UnaryUnaryMultiCallable[_acorn_rtc_pb2.SetRtcRegisterRequest, _acorn_rtc_pb2.SetRtcRegisterResponse]  # type: ignore[assignment]
    """Write a single register with a raw BCD value.
    The chip's per-register wrapping is applied faithfully.
    """
    WatchActivity: _aio.UnaryStreamMultiCallable[_acorn_rtc_pb2.WatchActivityRequest, _acorn_rtc_pb2.RtcActivityEvent]  # type: ignore[assignment]
    """Stream CBUS activity events (register reads and writes by the BBC).
    Analogous to watching the DATA LED on Ken Lowe's reproduction hardware.
    """

class AcornRtcServiceServicer(metaclass=_abc_1.ABCMeta):
    """Service for managing the SAF3019P Real Time Clock on the User Port."""

    @_abc_1.abstractmethod
    def GetTime(
        self,
        request: _acorn_rtc_pb2.GetRtcTimeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_acorn_rtc_pb2.GetRtcTimeResponse, _abc.Awaitable[_acorn_rtc_pb2.GetRtcTimeResponse]]:
        """Read the current emulated date and time (decoded from chip registers)."""

    @_abc_1.abstractmethod
    def SetTime(
        self,
        request: _acorn_rtc_pb2.SetRtcTimeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_acorn_rtc_pb2.SetRtcTimeResponse, _abc.Awaitable[_acorn_rtc_pb2.SetRtcTimeResponse]]:
        """Set the emulated date and time (writes all chip registers).
        Returns INVALID_ARGUMENT if the year is outside the representable
        range (1981-2000).
        """

    @_abc_1.abstractmethod
    def GetRegisters(
        self,
        request: _acorn_rtc_pb2.GetRtcRegistersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_acorn_rtc_pb2.GetRtcRegistersResponse, _abc.Awaitable[_acorn_rtc_pb2.GetRtcRegistersResponse]]:
        """Read all 8 raw BCD register values."""

    @_abc_1.abstractmethod
    def SetRegister(
        self,
        request: _acorn_rtc_pb2.SetRtcRegisterRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_acorn_rtc_pb2.SetRtcRegisterResponse, _abc.Awaitable[_acorn_rtc_pb2.SetRtcRegisterResponse]]:
        """Write a single register with a raw BCD value.
        The chip's per-register wrapping is applied faithfully.
        """

    @_abc_1.abstractmethod
    def WatchActivity(
        self,
        request: _acorn_rtc_pb2.WatchActivityRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_acorn_rtc_pb2.RtcActivityEvent], _abc.AsyncIterator[_acorn_rtc_pb2.RtcActivityEvent]]:
        """Stream CBUS activity events (register reads and writes by the BBC).
        Analogous to watching the DATA LED on Ken Lowe's reproduction hardware.
        """

def add_AcornRtcServiceServicer_to_server(servicer: AcornRtcServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...