# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from beebium._proto import acorn_rtc_pb2 as acorn__rtc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in acorn_rtc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AcornRtcServiceStub(object):
    """Service for managing the SAF3019P Real Time Clock on the User Port.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTime = channel.unary_unary(
                '/beebium.AcornRtcService/GetTime',
                request_serializer=acorn__rtc__pb2.GetRtcTimeRequest.SerializeToString,
                response_deserializer=acorn__rtc__pb2.GetRtcTimeResponse.FromString,
                _registered_method=True)
        self.SetTime = channel.unary_unary(
                '/beebium.AcornRtcService/SetTime',
                request_serializer=acorn__rtc__pb2.SetRtcTimeRequest.SerializeToString,
                response_deserializer=acorn__rtc__pb2.SetRtcTimeResponse.FromString,
                _registered_method=True)
        self.GetRegisters = channel.unary_unary(
                '/beebium.AcornRtcService/GetRegisters',
                request_serializer=acorn__rtc__pb2.GetRtcRegistersRequest.SerializeToString,
                response_deserializer=acorn__rtc__pb2.GetRtcRegistersResponse.FromString,
                _registered_method=True)
        self.SetRegister = channel.unary_unary(
                '/beebium.AcornRtcService/SetRegister',
                request_serializer=acorn__rtc__pb2.SetRtcRegisterRequest.SerializeToString,
                response_deserializer=acorn__rtc__pb2.SetRtcRegisterResponse.FromString,
                _registered_method=True)
        self.WatchActivity = channel.unary_stream(
                '/beebium.AcornRtcService/WatchActivity',
                request_serializer=acorn__rtc__pb2.WatchActivityRequest.SerializeToString,
                response_deserializer=acorn__rtc__pb2.RtcActivityEvent.FromString,
                _registered_method=True)


class AcornRtcServiceServicer(object):
    """Service for managing the SAF3019P Real Time Clock on the User Port.
    """

    def GetTime(self, request, context):
        """Read the current emulated date and time (decoded from chip registers).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTime(self, request, context):
        """Set the emulated date and time (writes all chip registers).
        Returns INVALID_ARGUMENT if the year is outside the representable
        range (1981-2000).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegisters(self, request, context):
        """Read all 8 raw BCD register values.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRegister(self, request, context):
        """Write a single register with a raw BCD value.
        The chip's per-register wrapping is applied faithfully.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchActivity(self, request, context):
        """Stream CBUS activity events (register reads and writes by the BBC).
        Analogous to watching the DATA LED on Ken Lowe's reproduction hardware.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcornRtcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=acorn__rtc__pb2.GetRtcTimeRequest.FromString,
                    response_serializer=acorn__rtc__pb2.GetRtcTimeResponse.SerializeToString,
            ),
            'SetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTime,
                    request_deserializer=acorn__rtc__pb2.SetRtcTimeRequest.FromString,
                    response_serializer=acorn__rtc__pb2.SetRtcTimeResponse.SerializeToString,
            ),
            'GetRegisters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegisters,
                    request_deserializer=acorn__rtc__pb2.GetRtcRegistersRequest.FromString,
                    response_serializer=acorn__rtc__pb2.GetRtcRegistersResponse.SerializeToString,
            ),
            'SetRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRegister,
                    request_deserializer=acorn__rtc__pb2.SetRtcRegisterRequest.FromString,
                    response_serializer=acorn__rtc__pb2.SetRtcRegisterResponse.SerializeToString,
            ),
            'WatchActivity': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchActivity,
                    request_deserializer=acorn__rtc__pb2.WatchActivityRequest.FromString,
                    response_serializer=acorn__rtc__pb2.RtcActivityEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.AcornRtcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.AcornRtcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AcornRtcService(object):
    """Service for managing the SAF3019P Real Time Clock on the User Port.
    """

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.AcornRtcService/GetTime',
            acorn__rtc__pb2.GetRtcTimeRequest.SerializeToString,
            acorn__rtc__pb2.GetRtcTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.AcornRtcService/SetTime',
            acorn__rtc__pb2.SetRtcTimeRequest.SerializeToString,
            acorn__rtc__pb2.SetRtcTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegisters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.AcornRtcService/GetRegisters',
            acorn__rtc__pb2.GetRtcRegistersRequest.SerializeToString,
            acorn__rtc__pb2.GetRtcRegistersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.AcornRtcService/SetRegister',
            acorn__rtc__pb2.SetRtcRegisterRequest.SerializeToString,
            acorn__rtc__pb2.SetRtcRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/beebium.AcornRtcService/WatchActivity',
            acorn__rtc__pb2.WatchActivityRequest.SerializeToString,
            acorn__rtc__pb2.RtcActivityEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
