# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import audio_pb2 as audio__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioServiceStub(object):
    """Audio streaming service
    Note: Sound chip state introspection moved to DebuggerControl.GetSoundChipState
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeAudio = channel.unary_stream(
                '/beebium.AudioService/SubscribeAudio',
                request_serializer=audio__pb2.SubscribeAudioRequest.SerializeToString,
                response_deserializer=audio__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.GetAudioFormat = channel.unary_unary(
                '/beebium.AudioService/GetAudioFormat',
                request_serializer=audio__pb2.GetAudioFormatRequest.SerializeToString,
                response_deserializer=audio__pb2.AudioFormat.FromString,
                _registered_method=True)


class AudioServiceServicer(object):
    """Audio streaming service
    Note: Sound chip state introspection moved to DebuggerControl.GetSoundChipState
    """

    def SubscribeAudio(self, request, context):
        """Stream audio samples as they're generated
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAudioFormat(self, request, context):
        """Get audio format metadata (how to interpret sample data)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeAudio,
                    request_deserializer=audio__pb2.SubscribeAudioRequest.FromString,
                    response_serializer=audio__pb2.AudioChunk.SerializeToString,
            ),
            'GetAudioFormat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAudioFormat,
                    request_deserializer=audio__pb2.GetAudioFormatRequest.FromString,
                    response_serializer=audio__pb2.AudioFormat.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.AudioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioService(object):
    """Audio streaming service
    Note: Sound chip state introspection moved to DebuggerControl.GetSoundChipState
    """

    @staticmethod
    def SubscribeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/beebium.AudioService/SubscribeAudio',
            audio__pb2.SubscribeAudioRequest.SerializeToString,
            audio__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAudioFormat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.AudioService/GetAudioFormat',
            audio__pb2.GetAudioFormatRequest.SerializeToString,
            audio__pb2.AudioFormat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
