# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import econet_pb2 as econet__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in econet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EconetServiceStub(object):
    """Econet/AUN networking management service.

    Provides hardware configuration (enable/disable Econet), network status
    queries (ADLC registers, handshake state), and AUN peer management.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEconetStatus = channel.unary_unary(
                '/beebium.EconetService/GetEconetStatus',
                request_serializer=econet__pb2.GetEconetStatusRequest.SerializeToString,
                response_deserializer=econet__pb2.GetEconetStatusResponse.FromString,
                _registered_method=True)
        self.EnableEconet = channel.unary_unary(
                '/beebium.EconetService/EnableEconet',
                request_serializer=econet__pb2.EnableEconetRequest.SerializeToString,
                response_deserializer=econet__pb2.EnableEconetResponse.FromString,
                _registered_method=True)
        self.DisableEconet = channel.unary_unary(
                '/beebium.EconetService/DisableEconet',
                request_serializer=econet__pb2.DisableEconetRequest.SerializeToString,
                response_deserializer=econet__pb2.DisableEconetResponse.FromString,
                _registered_method=True)
        self.SetStationId = channel.unary_unary(
                '/beebium.EconetService/SetStationId',
                request_serializer=econet__pb2.SetStationIdRequest.SerializeToString,
                response_deserializer=econet__pb2.SetStationIdResponse.FromString,
                _registered_method=True)
        self.SubscribeEconetEvents = channel.unary_stream(
                '/beebium.EconetService/SubscribeEconetEvents',
                request_serializer=econet__pb2.SubscribeEconetEventsRequest.SerializeToString,
                response_deserializer=econet__pb2.EconetEvent.FromString,
                _registered_method=True)
        self.WatchEconetStatus = channel.unary_stream(
                '/beebium.EconetService/WatchEconetStatus',
                request_serializer=econet__pb2.WatchEconetStatusRequest.SerializeToString,
                response_deserializer=econet__pb2.GetEconetStatusResponse.FromString,
                _registered_method=True)


class EconetServiceServicer(object):
    """Econet/AUN networking management service.

    Provides hardware configuration (enable/disable Econet), network status
    queries (ADLC registers, handshake state), and AUN peer management.
    """

    def GetEconetStatus(self, request, context):
        """Query Econet hardware status (enabled, station ID, ADLC state, peers).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableEconet(self, request, context):
        """Fit Econet hardware: set station ID, optionally bind AUN socket.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableEconet(self, request, context):
        """Remove Econet hardware (disable station, close AUN socket).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStationId(self, request, context):
        """Set the station ID (takes effect on next machine reset).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEconetEvents(self, request, context):
        """Stream Econet events (frame activity, handshake changes, connection state).
        Reserved for future implementation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEconetStatus(self, request, context):
        """Server-pushed status stream. Writes an initial GetEconetStatusResponse
        as soon as the stream is established, then a fresh snapshot whenever
        status visible on EconetService changes (enable/disable, station ID
        change, or transport backend connection toggle). The stream stays open
        until the client cancels; use this instead of polling GetEconetStatus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EconetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEconetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEconetStatus,
                    request_deserializer=econet__pb2.GetEconetStatusRequest.FromString,
                    response_serializer=econet__pb2.GetEconetStatusResponse.SerializeToString,
            ),
            'EnableEconet': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableEconet,
                    request_deserializer=econet__pb2.EnableEconetRequest.FromString,
                    response_serializer=econet__pb2.EnableEconetResponse.SerializeToString,
            ),
            'DisableEconet': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableEconet,
                    request_deserializer=econet__pb2.DisableEconetRequest.FromString,
                    response_serializer=econet__pb2.DisableEconetResponse.SerializeToString,
            ),
            'SetStationId': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStationId,
                    request_deserializer=econet__pb2.SetStationIdRequest.FromString,
                    response_serializer=econet__pb2.SetStationIdResponse.SerializeToString,
            ),
            'SubscribeEconetEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEconetEvents,
                    request_deserializer=econet__pb2.SubscribeEconetEventsRequest.FromString,
                    response_serializer=econet__pb2.EconetEvent.SerializeToString,
            ),
            'WatchEconetStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEconetStatus,
                    request_deserializer=econet__pb2.WatchEconetStatusRequest.FromString,
                    response_serializer=econet__pb2.GetEconetStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.EconetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.EconetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EconetService(object):
    """Econet/AUN networking management service.

    Provides hardware configuration (enable/disable Econet), network status
    queries (ADLC registers, handshake state), and AUN peer management.
    """

    @staticmethod
    def GetEconetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.EconetService/GetEconetStatus',
            econet__pb2.GetEconetStatusRequest.SerializeToString,
            econet__pb2.GetEconetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableEconet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.EconetService/EnableEconet',
            econet__pb2.EnableEconetRequest.SerializeToString,
            econet__pb2.EnableEconetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableEconet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.EconetService/DisableEconet',
            econet__pb2.DisableEconetRequest.SerializeToString,
            econet__pb2.DisableEconetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStationId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.EconetService/SetStationId',
            econet__pb2.SetStationIdRequest.SerializeToString,
            econet__pb2.SetStationIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEconetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/beebium.EconetService/SubscribeEconetEvents',
            econet__pb2.SubscribeEconetEventsRequest.SerializeToString,
            econet__pb2.EconetEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchEconetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/beebium.EconetService/WatchEconetStatus',
            econet__pb2.WatchEconetStatusRequest.SerializeToString,
            econet__pb2.GetEconetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)