# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import extension_ui_pb2 as extension__ui__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in extension_ui_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExtensionUiServiceStub(object):
    """Extension UI framework: a small, server-driven UI vocabulary that lets
    any extension (peripheral, econet transport, future kinds) describe a
    control panel as a typed tree of Controls. Frontends render the tree
    natively and post user actions back through Dispatch.

    Design notes: docs/discussion/extension-ui-architecture.md

    The model is server-driven (Phoenix-LiveView style): the server holds
    the extension's state and computes a View; the client is a thin
    renderer with no business state. All user actions route through one
    Dispatch RPC -- there are no per-control RPCs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeView = channel.unary_stream(
                '/beebium.ExtensionUiService/SubscribeView',
                request_serializer=extension__ui__pb2.SubscribeViewRequest.SerializeToString,
                response_deserializer=extension__ui__pb2.View.FromString,
                _registered_method=True)
        self.Dispatch = channel.unary_unary(
                '/beebium.ExtensionUiService/Dispatch',
                request_serializer=extension__ui__pb2.DispatchRequest.SerializeToString,
                response_deserializer=extension__ui__pb2.DispatchResponse.FromString,
                _registered_method=True)


class ExtensionUiServiceServicer(object):
    """Extension UI framework: a small, server-driven UI vocabulary that lets
    any extension (peripheral, econet transport, future kinds) describe a
    control panel as a typed tree of Controls. Frontends render the tree
    natively and post user actions back through Dispatch.

    Design notes: docs/discussion/extension-ui-architecture.md

    The model is server-driven (Phoenix-LiveView style): the server holds
    the extension's state and computes a View; the client is a thin
    renderer with no business state. All user actions route through one
    Dispatch RPC -- there are no per-control RPCs.
    """

    def SubscribeView(self, request, context):
        """Open a long-lived stream of View updates for one extension. The
        server pushes a fresh View whenever the extension's state changes
        (the first View is delivered immediately on subscription). The
        stream ends with NOT_FOUND if the named extension does not exist
        (or is unloaded mid-session).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dispatch(self, request, context):
        """Post a user action back to the server. The server validates the
        request (extension exists, control id is known for the current
        view revision, payload type matches the control type, revision is
        current) and then runs the extension's handle_event. The result of
        the action is observable on the SubscribeView stream as a new
        View, not in the response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtensionUiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeView': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeView,
                    request_deserializer=extension__ui__pb2.SubscribeViewRequest.FromString,
                    response_serializer=extension__ui__pb2.View.SerializeToString,
            ),
            'Dispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.Dispatch,
                    request_deserializer=extension__ui__pb2.DispatchRequest.FromString,
                    response_serializer=extension__ui__pb2.DispatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.ExtensionUiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.ExtensionUiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExtensionUiService(object):
    """Extension UI framework: a small, server-driven UI vocabulary that lets
    any extension (peripheral, econet transport, future kinds) describe a
    control panel as a typed tree of Controls. Frontends render the tree
    natively and post user actions back through Dispatch.

    Design notes: docs/discussion/extension-ui-architecture.md

    The model is server-driven (Phoenix-LiveView style): the server holds
    the extension's state and computes a View; the client is a thin
    renderer with no business state. All user actions route through one
    Dispatch RPC -- there are no per-control RPCs.
    """

    @staticmethod
    def SubscribeView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/beebium.ExtensionUiService/SubscribeView',
            extension__ui__pb2.SubscribeViewRequest.SerializeToString,
            extension__ui__pb2.View.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.ExtensionUiService/Dispatch',
            extension__ui__pb2.DispatchRequest.SerializeToString,
            extension__ui__pb2.DispatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)