# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import extension_rpc_pb2 as extension__rpc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in extension_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExtensionRpcStub(object):
    """The one generic, core-hosted service through which clients drive
    extension-provided APIs. Extensions never host a gRPC service themselves;
    they register C++ dispatchers and the core tunnels opaque serialized
    request/response bytes to them. This keeps the single gRPC runtime in the
    core, so a plugin never links gRPC. The extension's own request/response
    messages are ordinary protobuf, but they travel as opaque `payload` bytes
    here -- only the extension and the client (de)serialize them.

    See docs/discussion/extension-rpc-channel.md.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/beebium.ExtensionRpc/Invoke',
                request_serializer=extension__rpc__pb2.InvokeRequest.SerializeToString,
                response_deserializer=extension__rpc__pb2.InvokeResponse.FromString,
                _registered_method=True)
        self.ServerStream = channel.unary_stream(
                '/beebium.ExtensionRpc/ServerStream',
                request_serializer=extension__rpc__pb2.InvokeRequest.SerializeToString,
                response_deserializer=extension__rpc__pb2.InvokeResponse.FromString,
                _registered_method=True)


class ExtensionRpcServicer(object):
    """The one generic, core-hosted service through which clients drive
    extension-provided APIs. Extensions never host a gRPC service themselves;
    they register C++ dispatchers and the core tunnels opaque serialized
    request/response bytes to them. This keeps the single gRPC runtime in the
    core, so a plugin never links gRPC. The extension's own request/response
    messages are ordinary protobuf, but they travel as opaque `payload` bytes
    here -- only the extension and the client (de)serialize them.

    See docs/discussion/extension-rpc-channel.md.
    """

    def Invoke(self, request, context):
        """Unary: one request, one response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStream(self, request, context):
        """Server-streaming: one request, a stream of responses (status feeds,
        event subscriptions).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtensionRpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=extension__rpc__pb2.InvokeRequest.FromString,
                    response_serializer=extension__rpc__pb2.InvokeResponse.SerializeToString,
            ),
            'ServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStream,
                    request_deserializer=extension__rpc__pb2.InvokeRequest.FromString,
                    response_serializer=extension__rpc__pb2.InvokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.ExtensionRpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.ExtensionRpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExtensionRpc(object):
    """The one generic, core-hosted service through which clients drive
    extension-provided APIs. Extensions never host a gRPC service themselves;
    they register C++ dispatchers and the core tunnels opaque serialized
    request/response bytes to them. This keeps the single gRPC runtime in the
    core, so a plugin never links gRPC. The extension's own request/response
    messages are ordinary protobuf, but they travel as opaque `payload` bytes
    here -- only the extension and the client (de)serialize them.

    See docs/discussion/extension-rpc-channel.md.
    """

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.ExtensionRpc/Invoke',
            extension__rpc__pb2.InvokeRequest.SerializeToString,
            extension__rpc__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/beebium.ExtensionRpc/ServerStream',
            extension__rpc__pb2.InvokeRequest.SerializeToString,
            extension__rpc__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)