# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: extension_rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'extension_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65xtension_rpc.proto\x12\x07\x62\x65\x65\x62ium\"\xc0\x01\n\rInvokeRequest\x12\x14\n\x0c\x65xtension_id\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x36\n\x08metadata\x18\x05 \x03(\x0b\x32$.beebium.InvokeRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\x0eInvokeResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x32\x8c\x01\n\x0c\x45xtensionRpc\x12\x39\n\x06Invoke\x12\x16.beebium.InvokeRequest\x1a\x17.beebium.InvokeResponse\x12\x41\n\x0cServerStream\x12\x16.beebium.InvokeRequest\x1a\x17.beebium.InvokeResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extension_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOKEREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_INVOKEREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INVOKEREQUEST']._serialized_start=33
  _globals['_INVOKEREQUEST']._serialized_end=225
  _globals['_INVOKEREQUEST_METADATAENTRY']._serialized_start=178
  _globals['_INVOKEREQUEST_METADATAENTRY']._serialized_end=225
  _globals['_INVOKERESPONSE']._serialized_start=227
  _globals['_INVOKERESPONSE']._serialized_end=260
  _globals['_EXTENSIONRPC']._serialized_start=263
  _globals['_EXTENSIONRPC']._serialized_end=403
# @@protoc_insertion_point(module_scope)