# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import host_serial_pb2 as host__serial__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in host_serial_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HostSerialStub(object):
    """Typed config API for the host-serial extension: query and re-point the host
    serial bridge (mode / path / baud) without going through the GUI ExtensionUi
    path. This service belongs to the host-serial PeripheralExtension and is
    present only when --host-serial is loaded. It drives the SAME underlying
    re-point path (HostSerialEndpoint::request_reopen) as the GUI editor, so a
    SetConfig and a GUI edit are equivalent and each is reflected in the other.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfig = channel.unary_unary(
                '/beebium.HostSerial/GetConfig',
                request_serializer=host__serial__pb2.HostSerialGetConfigRequest.SerializeToString,
                response_deserializer=host__serial__pb2.HostSerialConfig.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/beebium.HostSerial/SetConfig',
                request_serializer=host__serial__pb2.HostSerialSetConfigRequest.SerializeToString,
                response_deserializer=host__serial__pb2.HostSerialConfig.FromString,
                _registered_method=True)


class HostSerialServicer(object):
    """Typed config API for the host-serial extension: query and re-point the host
    serial bridge (mode / path / baud) without going through the GUI ExtensionUi
    path. This service belongs to the host-serial PeripheralExtension and is
    present only when --host-serial is loaded. It drives the SAME underlying
    re-point path (HostSerialEndpoint::request_reopen) as the GUI editor, so a
    SetConfig and a GUI edit are equivalent and each is reflected in the other.
    """

    def GetConfig(self, request, context):
        """Read the current bridge configuration and open state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Re-point the bridge. A partial update: only the fields present in the
        request change; the rest are kept (the client sends just the diff). The
        re-point is applied asynchronously on the next emulation tick, so the
        returned config is a snapshot taken at call time and may still show the
        previous device until the re-point lands -- call GetConfig to confirm.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostSerialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=host__serial__pb2.HostSerialGetConfigRequest.FromString,
                    response_serializer=host__serial__pb2.HostSerialConfig.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=host__serial__pb2.HostSerialSetConfigRequest.FromString,
                    response_serializer=host__serial__pb2.HostSerialConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.HostSerial', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.HostSerial', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostSerial(object):
    """Typed config API for the host-serial extension: query and re-point the host
    serial bridge (mode / path / baud) without going through the GUI ExtensionUi
    path. This service belongs to the host-serial PeripheralExtension and is
    present only when --host-serial is loaded. It drives the SAME underlying
    re-point path (HostSerialEndpoint::request_reopen) as the GUI editor, so a
    SetConfig and a GUI edit are equivalent and each is reflected in the other.
    """

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.HostSerial/GetConfig',
            host__serial__pb2.HostSerialGetConfigRequest.SerializeToString,
            host__serial__pb2.HostSerialConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.HostSerial/SetConfig',
            host__serial__pb2.HostSerialSetConfigRequest.SerializeToString,
            host__serial__pb2.HostSerialConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)