# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: indicator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'indicator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0findicator.proto\x12\x07\x62\x65\x65\x62ium\"0\n\x14GetIndicatorsRequest\x12\x18\n\x10if_changed_since\x18\x01 \x01(\x04\"\xa5\x01\n\x15GetIndicatorsResponse\x12:\n\x06values\x18\x01 \x03(\x0b\x32*.beebium.GetIndicatorsResponse.ValuesEntry\x12\x10\n\x08sequence\x18\x02 \x01(\x04\x12\x0f\n\x07\x63hanged\x18\x03 \x01(\x08\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"\x17\n\x15ListIndicatorsRequest\"D\n\x16ListIndicatorsResponse\x12*\n\nindicators\x18\x01 \x03(\x0b\x32\x16.beebium.IndicatorInfo\"\x86\x01\n\rIndicatorInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x36\n\x08metadata\x18\x02 \x03(\x0b\x32$.beebium.IndicatorInfo.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"D\n\x1aSubscribeIndicatorsRequest\x12\r\n\x05names\x18\x01 \x03(\t\x12\x17\n\x0fmin_interval_ms\x18\x02 \x01(\r\"\x88\x01\n\x0fIndicatorUpdate\x12\x34\n\x06values\x18\x01 \x03(\x0b\x32$.beebium.IndicatorUpdate.ValuesEntry\x12\x10\n\x08sequence\x18\x02 \x01(\x04\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x32\x83\x02\n\x10IndicatorService\x12N\n\rGetIndicators\x12\x1d.beebium.GetIndicatorsRequest\x1a\x1e.beebium.GetIndicatorsResponse\x12Q\n\x0eListIndicators\x12\x1e.beebium.ListIndicatorsRequest\x1a\x1f.beebium.ListIndicatorsResponse\x12L\n\tSubscribe\x12#.beebium.SubscribeIndicatorsRequest\x1a\x18.beebium.IndicatorUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indicator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETINDICATORSRESPONSE_VALUESENTRY']._loaded_options = None
  _globals['_GETINDICATORSRESPONSE_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_INDICATORINFO_METADATAENTRY']._loaded_options = None
  _globals['_INDICATORINFO_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INDICATORUPDATE_VALUESENTRY']._loaded_options = None
  _globals['_INDICATORUPDATE_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_GETINDICATORSREQUEST']._serialized_start=28
  _globals['_GETINDICATORSREQUEST']._serialized_end=76
  _globals['_GETINDICATORSRESPONSE']._serialized_start=79
  _globals['_GETINDICATORSRESPONSE']._serialized_end=244
  _globals['_GETINDICATORSRESPONSE_VALUESENTRY']._serialized_start=199
  _globals['_GETINDICATORSRESPONSE_VALUESENTRY']._serialized_end=244
  _globals['_LISTINDICATORSREQUEST']._serialized_start=246
  _globals['_LISTINDICATORSREQUEST']._serialized_end=269
  _globals['_LISTINDICATORSRESPONSE']._serialized_start=271
  _globals['_LISTINDICATORSRESPONSE']._serialized_end=339
  _globals['_INDICATORINFO']._serialized_start=342
  _globals['_INDICATORINFO']._serialized_end=476
  _globals['_INDICATORINFO_METADATAENTRY']._serialized_start=429
  _globals['_INDICATORINFO_METADATAENTRY']._serialized_end=476
  _globals['_SUBSCRIBEINDICATORSREQUEST']._serialized_start=478
  _globals['_SUBSCRIBEINDICATORSREQUEST']._serialized_end=546
  _globals['_INDICATORUPDATE']._serialized_start=549
  _globals['_INDICATORUPDATE']._serialized_end=685
  _globals['_INDICATORUPDATE_VALUESENTRY']._serialized_start=199
  _globals['_INDICATORUPDATE_VALUESENTRY']._serialized_end=244
  _globals['_INDICATORSERVICE']._serialized_start=688
  _globals['_INDICATORSERVICE']._serialized_end=947
# @@protoc_insertion_point(module_scope)