# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import indicator_pb2 as indicator__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in indicator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IndicatorServiceStub(object):
    """Hardware indicator state service.

    Exposes observable hardware state (LEDs, motor activity) to frontends.
    Indicators are identified by string names (e.g., "caps-lock-led",
    "floppy-0-activity-led") and have configurable filtering (debounce,
    duty-cycle averaging) applied server-side.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIndicators = channel.unary_unary(
                '/beebium.IndicatorService/GetIndicators',
                request_serializer=indicator__pb2.GetIndicatorsRequest.SerializeToString,
                response_deserializer=indicator__pb2.GetIndicatorsResponse.FromString,
                _registered_method=True)
        self.ListIndicators = channel.unary_unary(
                '/beebium.IndicatorService/ListIndicators',
                request_serializer=indicator__pb2.ListIndicatorsRequest.SerializeToString,
                response_deserializer=indicator__pb2.ListIndicatorsResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/beebium.IndicatorService/Subscribe',
                request_serializer=indicator__pb2.SubscribeIndicatorsRequest.SerializeToString,
                response_deserializer=indicator__pb2.IndicatorUpdate.FromString,
                _registered_method=True)


class IndicatorServiceServicer(object):
    """Hardware indicator state service.

    Exposes observable hardware state (LEDs, motor activity) to frontends.
    Indicators are identified by string names (e.g., "caps-lock-led",
    "floppy-0-activity-led") and have configurable filtering (debounce,
    duty-cycle averaging) applied server-side.
    """

    def GetIndicators(self, request, context):
        """Get current values of all indicators.
        Supports conditional fetch via if_changed_since for efficient polling.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIndicators(self, request, context):
        """List all registered indicators with their metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Stream indicator value changes in real-time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndicatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIndicators': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndicators,
                    request_deserializer=indicator__pb2.GetIndicatorsRequest.FromString,
                    response_serializer=indicator__pb2.GetIndicatorsResponse.SerializeToString,
            ),
            'ListIndicators': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIndicators,
                    request_deserializer=indicator__pb2.ListIndicatorsRequest.FromString,
                    response_serializer=indicator__pb2.ListIndicatorsResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=indicator__pb2.SubscribeIndicatorsRequest.FromString,
                    response_serializer=indicator__pb2.IndicatorUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.IndicatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.IndicatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IndicatorService(object):
    """Hardware indicator state service.

    Exposes observable hardware state (LEDs, motor activity) to frontends.
    Indicators are identified by string names (e.g., "caps-lock-led",
    "floppy-0-activity-led") and have configurable filtering (debounce,
    duty-cycle averaging) applied server-side.
    """

    @staticmethod
    def GetIndicators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.IndicatorService/GetIndicators',
            indicator__pb2.GetIndicatorsRequest.SerializeToString,
            indicator__pb2.GetIndicatorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIndicators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.IndicatorService/ListIndicators',
            indicator__pb2.ListIndicatorsRequest.SerializeToString,
            indicator__pb2.ListIndicatorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/beebium.IndicatorService/Subscribe',
            indicator__pb2.SubscribeIndicatorsRequest.SerializeToString,
            indicator__pb2.IndicatorUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)