# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import keyboard_pb2 as keyboard__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in keyboard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeyboardServiceStub(object):
    """BBC keyboard matrix input service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.KeyDown = channel.unary_unary(
                '/beebium.KeyboardService/KeyDown',
                request_serializer=keyboard__pb2.KeyRequest.SerializeToString,
                response_deserializer=keyboard__pb2.KeyResponse.FromString,
                _registered_method=True)
        self.KeyUp = channel.unary_unary(
                '/beebium.KeyboardService/KeyUp',
                request_serializer=keyboard__pb2.KeyRequest.SerializeToString,
                response_deserializer=keyboard__pb2.KeyResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/beebium.KeyboardService/GetState',
                request_serializer=keyboard__pb2.GetStateRequest.SerializeToString,
                response_deserializer=keyboard__pb2.KeyboardState.FromString,
                _registered_method=True)
        self.SetLinks = channel.unary_unary(
                '/beebium.KeyboardService/SetLinks',
                request_serializer=keyboard__pb2.SetLinksRequest.SerializeToString,
                response_deserializer=keyboard__pb2.SetLinksResponse.FromString,
                _registered_method=True)
        self.GetLinks = channel.unary_unary(
                '/beebium.KeyboardService/GetLinks',
                request_serializer=keyboard__pb2.GetLinksRequest.SerializeToString,
                response_deserializer=keyboard__pb2.LinksState.FromString,
                _registered_method=True)
        self.SetStartupScreenMode = channel.unary_unary(
                '/beebium.KeyboardService/SetStartupScreenMode',
                request_serializer=keyboard__pb2.SetStartupScreenModeRequest.SerializeToString,
                response_deserializer=keyboard__pb2.SetStartupScreenModeResponse.FromString,
                _registered_method=True)
        self.GetStartupScreenMode = channel.unary_unary(
                '/beebium.KeyboardService/GetStartupScreenMode',
                request_serializer=keyboard__pb2.GetStartupScreenModeRequest.SerializeToString,
                response_deserializer=keyboard__pb2.StartupScreenModeState.FromString,
                _registered_method=True)
        self.SetStartupAutoBoot = channel.unary_unary(
                '/beebium.KeyboardService/SetStartupAutoBoot',
                request_serializer=keyboard__pb2.SetStartupAutoBootRequest.SerializeToString,
                response_deserializer=keyboard__pb2.SetStartupAutoBootResponse.FromString,
                _registered_method=True)
        self.GetStartupAutoBoot = channel.unary_unary(
                '/beebium.KeyboardService/GetStartupAutoBoot',
                request_serializer=keyboard__pb2.GetStartupAutoBootRequest.SerializeToString,
                response_deserializer=keyboard__pb2.StartupAutoBootState.FromString,
                _registered_method=True)
        self.TypeQuickly = channel.unary_unary(
                '/beebium.KeyboardService/TypeQuickly',
                request_serializer=keyboard__pb2.TypeQuicklyRequest.SerializeToString,
                response_deserializer=keyboard__pb2.TypeQuicklyResponse.FromString,
                _registered_method=True)
        self.GetTypingStatus = channel.unary_unary(
                '/beebium.KeyboardService/GetTypingStatus',
                request_serializer=keyboard__pb2.GetTypingStatusRequest.SerializeToString,
                response_deserializer=keyboard__pb2.TypingStatus.FromString,
                _registered_method=True)
        self.ClearTyping = channel.unary_unary(
                '/beebium.KeyboardService/ClearTyping',
                request_serializer=keyboard__pb2.ClearTypingRequest.SerializeToString,
                response_deserializer=keyboard__pb2.ClearTypingResponse.FromString,
                _registered_method=True)
        self.GetKeyMapping = channel.unary_unary(
                '/beebium.KeyboardService/GetKeyMapping',
                request_serializer=keyboard__pb2.GetKeyMappingRequest.SerializeToString,
                response_deserializer=keyboard__pb2.KeyMappingEntry.FromString,
                _registered_method=True)
        self.GetAllKeyMappings = channel.unary_unary(
                '/beebium.KeyboardService/GetAllKeyMappings',
                request_serializer=keyboard__pb2.GetAllKeyMappingsRequest.SerializeToString,
                response_deserializer=keyboard__pb2.AllKeyMappingsResponse.FromString,
                _registered_method=True)


class KeyboardServiceServicer(object):
    """BBC keyboard matrix input service
    """

    def KeyDown(self, request, context):
        """Press/release by matrix position (momentary key events)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KeyUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Query current pressed keys
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLinks(self, request, context):
        """=========================================================================
        Keyboard Links (DIP switches)
        =========================================================================
        These are persistent configuration settings, not momentary key events.
        The 8 links form a startup options byte read by MOS at reset.

        Raw byte access to all 8 links
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStartupScreenMode(self, request, context):
        """Semantic accessors for specific link groups
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStartupScreenMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStartupAutoBoot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStartupAutoBoot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TypeQuickly(self, request, context):
        """=========================================================================
        Type-ahead (TypeQuickly)
        =========================================================================
        Non-blocking text input that types strings at machine speed.
        Text is queued and typed character-by-character as the emulator runs.

        Enqueue text to type at machine speed (non-blocking)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTypingStatus(self, request, context):
        """Query typing status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearTyping(self, request, context):
        """Clear pending typing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKeyMapping(self, request, context):
        """=========================================================================
        Character-to-key mapping
        =========================================================================
        Query the canonical character-to-key mapping table.

        Get mapping for a single character
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllKeyMappings(self, request, context):
        """Get complete mapping table (for client caching)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyboardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'KeyDown': grpc.unary_unary_rpc_method_handler(
                    servicer.KeyDown,
                    request_deserializer=keyboard__pb2.KeyRequest.FromString,
                    response_serializer=keyboard__pb2.KeyResponse.SerializeToString,
            ),
            'KeyUp': grpc.unary_unary_rpc_method_handler(
                    servicer.KeyUp,
                    request_deserializer=keyboard__pb2.KeyRequest.FromString,
                    response_serializer=keyboard__pb2.KeyResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=keyboard__pb2.GetStateRequest.FromString,
                    response_serializer=keyboard__pb2.KeyboardState.SerializeToString,
            ),
            'SetLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLinks,
                    request_deserializer=keyboard__pb2.SetLinksRequest.FromString,
                    response_serializer=keyboard__pb2.SetLinksResponse.SerializeToString,
            ),
            'GetLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLinks,
                    request_deserializer=keyboard__pb2.GetLinksRequest.FromString,
                    response_serializer=keyboard__pb2.LinksState.SerializeToString,
            ),
            'SetStartupScreenMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStartupScreenMode,
                    request_deserializer=keyboard__pb2.SetStartupScreenModeRequest.FromString,
                    response_serializer=keyboard__pb2.SetStartupScreenModeResponse.SerializeToString,
            ),
            'GetStartupScreenMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStartupScreenMode,
                    request_deserializer=keyboard__pb2.GetStartupScreenModeRequest.FromString,
                    response_serializer=keyboard__pb2.StartupScreenModeState.SerializeToString,
            ),
            'SetStartupAutoBoot': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStartupAutoBoot,
                    request_deserializer=keyboard__pb2.SetStartupAutoBootRequest.FromString,
                    response_serializer=keyboard__pb2.SetStartupAutoBootResponse.SerializeToString,
            ),
            'GetStartupAutoBoot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStartupAutoBoot,
                    request_deserializer=keyboard__pb2.GetStartupAutoBootRequest.FromString,
                    response_serializer=keyboard__pb2.StartupAutoBootState.SerializeToString,
            ),
            'TypeQuickly': grpc.unary_unary_rpc_method_handler(
                    servicer.TypeQuickly,
                    request_deserializer=keyboard__pb2.TypeQuicklyRequest.FromString,
                    response_serializer=keyboard__pb2.TypeQuicklyResponse.SerializeToString,
            ),
            'GetTypingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTypingStatus,
                    request_deserializer=keyboard__pb2.GetTypingStatusRequest.FromString,
                    response_serializer=keyboard__pb2.TypingStatus.SerializeToString,
            ),
            'ClearTyping': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearTyping,
                    request_deserializer=keyboard__pb2.ClearTypingRequest.FromString,
                    response_serializer=keyboard__pb2.ClearTypingResponse.SerializeToString,
            ),
            'GetKeyMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKeyMapping,
                    request_deserializer=keyboard__pb2.GetKeyMappingRequest.FromString,
                    response_serializer=keyboard__pb2.KeyMappingEntry.SerializeToString,
            ),
            'GetAllKeyMappings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllKeyMappings,
                    request_deserializer=keyboard__pb2.GetAllKeyMappingsRequest.FromString,
                    response_serializer=keyboard__pb2.AllKeyMappingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.KeyboardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.KeyboardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyboardService(object):
    """BBC keyboard matrix input service
    """

    @staticmethod
    def KeyDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/KeyDown',
            keyboard__pb2.KeyRequest.SerializeToString,
            keyboard__pb2.KeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KeyUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/KeyUp',
            keyboard__pb2.KeyRequest.SerializeToString,
            keyboard__pb2.KeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/GetState',
            keyboard__pb2.GetStateRequest.SerializeToString,
            keyboard__pb2.KeyboardState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/SetLinks',
            keyboard__pb2.SetLinksRequest.SerializeToString,
            keyboard__pb2.SetLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/GetLinks',
            keyboard__pb2.GetLinksRequest.SerializeToString,
            keyboard__pb2.LinksState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStartupScreenMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/SetStartupScreenMode',
            keyboard__pb2.SetStartupScreenModeRequest.SerializeToString,
            keyboard__pb2.SetStartupScreenModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStartupScreenMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/GetStartupScreenMode',
            keyboard__pb2.GetStartupScreenModeRequest.SerializeToString,
            keyboard__pb2.StartupScreenModeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStartupAutoBoot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/SetStartupAutoBoot',
            keyboard__pb2.SetStartupAutoBootRequest.SerializeToString,
            keyboard__pb2.SetStartupAutoBootResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStartupAutoBoot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/GetStartupAutoBoot',
            keyboard__pb2.GetStartupAutoBootRequest.SerializeToString,
            keyboard__pb2.StartupAutoBootState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TypeQuickly(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/TypeQuickly',
            keyboard__pb2.TypeQuicklyRequest.SerializeToString,
            keyboard__pb2.TypeQuicklyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTypingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/GetTypingStatus',
            keyboard__pb2.GetTypingStatusRequest.SerializeToString,
            keyboard__pb2.TypingStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearTyping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/ClearTyping',
            keyboard__pb2.ClearTypingRequest.SerializeToString,
            keyboard__pb2.ClearTypingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKeyMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/GetKeyMapping',
            keyboard__pb2.GetKeyMappingRequest.SerializeToString,
            keyboard__pb2.KeyMappingEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllKeyMappings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.KeyboardService/GetAllKeyMappings',
            keyboard__pb2.GetAllKeyMappingsRequest.SerializeToString,
            keyboard__pb2.AllKeyMappingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
