# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: piconet_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'piconet_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15piconet_service.proto\x12\x07\x62\x65\x65\x62ium\"\x19\n\x17PiconetGetStatusRequest\"D\n\x18PiconetGetStatusResponse\x12\x13\n\x0b\x64\x65vice_path\x18\x01 \x01(\t\x12\x13\n\x0bserial_open\x18\x02 \x01(\x08\x32\x62\n\x0ePiconetService\x12P\n\tGetStatus\x12 .beebium.PiconetGetStatusRequest\x1a!.beebium.PiconetGetStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'piconet_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PICONETGETSTATUSREQUEST']._serialized_start=34
  _globals['_PICONETGETSTATUSREQUEST']._serialized_end=59
  _globals['_PICONETGETSTATUSRESPONSE']._serialized_start=61
  _globals['_PICONETGETSTATUSRESPONSE']._serialized_end=129
  _globals['_PICONETSERVICE']._serialized_start=131
  _globals['_PICONETSERVICE']._serialized_end=229
# @@protoc_insertion_point(module_scope)