# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import piconet_service_pb2 as piconet__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in piconet_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PiconetServiceStub(object):
    """Piconet-specific service. Lives alongside PiconetEconetTransportExtension
    in src/extensions/piconet/ and is registered via the extension's
    grpc_services() hook so the gRPC server only exposes it when Piconet
    is the active transport.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for Piconet (the USB serial bridge to a real Econet wire) lives here.

    Initial scope is intentionally minimal -- just enough for a user
    to confirm "yes, my Piconet is plugged in, and it's on /dev/X".
    Once the service exists it can grow without further architectural
    work; expansion possibilities are listed at the bottom of this file.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/beebium.PiconetService/GetStatus',
                request_serializer=piconet__service__pb2.PiconetGetStatusRequest.SerializeToString,
                response_deserializer=piconet__service__pb2.PiconetGetStatusResponse.FromString,
                _registered_method=True)


class PiconetServiceServicer(object):
    """Piconet-specific service. Lives alongside PiconetEconetTransportExtension
    in src/extensions/piconet/ and is registered via the extension's
    grpc_services() hook so the gRPC server only exposes it when Piconet
    is the active transport.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for Piconet (the USB serial bridge to a real Econet wire) lives here.

    Initial scope is intentionally minimal -- just enough for a user
    to confirm "yes, my Piconet is plugged in, and it's on /dev/X".
    Once the service exists it can grow without further architectural
    work; expansion possibilities are listed at the bottom of this file.

    """

    def GetStatus(self, request, context):
        """Read the current Piconet adapter state. Returns immediately;
        does not touch the serial wire.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PiconetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=piconet__service__pb2.PiconetGetStatusRequest.FromString,
                    response_serializer=piconet__service__pb2.PiconetGetStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.PiconetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.PiconetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PiconetService(object):
    """Piconet-specific service. Lives alongside PiconetEconetTransportExtension
    in src/extensions/piconet/ and is registered via the extension's
    grpc_services() hook so the gRPC server only exposes it when Piconet
    is the active transport.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for Piconet (the USB serial bridge to a real Econet wire) lives here.

    Initial scope is intentionally minimal -- just enough for a user
    to confirm "yes, my Piconet is plugged in, and it's on /dev/X".
    Once the service exists it can grow without further architectural
    work; expansion possibilities are listed at the bottom of this file.

    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.PiconetService/GetStatus',
            piconet__service__pb2.PiconetGetStatusRequest.SerializeToString,
            piconet__service__pb2.PiconetGetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)