# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rpc_serial_pb2 as rpc__serial__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rpc_serial_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RpcSerialStub(object):
    """Client-driven serial peer ("rpc-serial"): the RPC client is the device on the
    far end of the BBC's serial wire. The client injects bytes for the BBC to
    receive (Send) and collects bytes the BBC has transmitted (Receive). This
    service belongs to the rpc-serial PeripheralExtension, which owns the endpoint.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/beebium.RpcSerial/Send',
                request_serializer=rpc__serial__pb2.RpcSerialSendRequest.SerializeToString,
                response_deserializer=rpc__serial__pb2.RpcSerialSendResponse.FromString,
                _registered_method=True)
        self.Receive = channel.unary_unary(
                '/beebium.RpcSerial/Receive',
                request_serializer=rpc__serial__pb2.RpcSerialReceiveRequest.SerializeToString,
                response_deserializer=rpc__serial__pb2.RpcSerialReceiveResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/beebium.RpcSerial/GetStatus',
                request_serializer=rpc__serial__pb2.RpcSerialStatusRequest.SerializeToString,
                response_deserializer=rpc__serial__pb2.RpcSerialStatus.FromString,
                _registered_method=True)


class RpcSerialServicer(object):
    """Client-driven serial peer ("rpc-serial"): the RPC client is the device on the
    far end of the BBC's serial wire. The client injects bytes for the BBC to
    receive (Send) and collects bytes the BBC has transmitted (Receive). This
    service belongs to the rpc-serial PeripheralExtension, which owns the endpoint.
    """

    def Send(self, request, context):
        """Inject bytes for the BBC to receive (device -> Beeb).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Receive(self, request, context):
        """Collect bytes the BBC has transmitted (Beeb -> device).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Pending byte counts in each direction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RpcSerialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=rpc__serial__pb2.RpcSerialSendRequest.FromString,
                    response_serializer=rpc__serial__pb2.RpcSerialSendResponse.SerializeToString,
            ),
            'Receive': grpc.unary_unary_rpc_method_handler(
                    servicer.Receive,
                    request_deserializer=rpc__serial__pb2.RpcSerialReceiveRequest.FromString,
                    response_serializer=rpc__serial__pb2.RpcSerialReceiveResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=rpc__serial__pb2.RpcSerialStatusRequest.FromString,
                    response_serializer=rpc__serial__pb2.RpcSerialStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.RpcSerial', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.RpcSerial', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RpcSerial(object):
    """Client-driven serial peer ("rpc-serial"): the RPC client is the device on the
    far end of the BBC's serial wire. The client injects bytes for the BBC to
    receive (Send) and collects bytes the BBC has transmitted (Receive). This
    service belongs to the rpc-serial PeripheralExtension, which owns the endpoint.
    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.RpcSerial/Send',
            rpc__serial__pb2.RpcSerialSendRequest.SerializeToString,
            rpc__serial__pb2.RpcSerialSendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Receive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.RpcSerial/Receive',
            rpc__serial__pb2.RpcSerialReceiveRequest.SerializeToString,
            rpc__serial__pb2.RpcSerialReceiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.RpcSerial/GetStatus',
            rpc__serial__pb2.RpcSerialStatusRequest.SerializeToString,
            rpc__serial__pb2.RpcSerialStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)