# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpc_serial.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rpc_serial.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rpc_serial.proto\x12\x07\x62\x65\x65\x62ium\"$\n\x14RpcSerialSendRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\'\n\x15RpcSerialSendResponse\x12\x0e\n\x06queued\x18\x01 \x01(\r\",\n\x17RpcSerialReceiveRequest\x12\x11\n\tmax_bytes\x18\x01 \x01(\r\"(\n\x18RpcSerialReceiveResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x18\n\x16RpcSerialStatusRequest\"9\n\x0fRpcSerialStatus\x12\x12\n\ntx_pending\x18\x01 \x01(\r\x12\x12\n\nrx_pending\x18\x02 \x01(\r2\xea\x01\n\tRpcSerial\x12\x45\n\x04Send\x12\x1d.beebium.RpcSerialSendRequest\x1a\x1e.beebium.RpcSerialSendResponse\x12N\n\x07Receive\x12 .beebium.RpcSerialReceiveRequest\x1a!.beebium.RpcSerialReceiveResponse\x12\x46\n\tGetStatus\x12\x1f.beebium.RpcSerialStatusRequest\x1a\x18.beebium.RpcSerialStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_serial_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RPCSERIALSENDREQUEST']._serialized_start=29
  _globals['_RPCSERIALSENDREQUEST']._serialized_end=65
  _globals['_RPCSERIALSENDRESPONSE']._serialized_start=67
  _globals['_RPCSERIALSENDRESPONSE']._serialized_end=106
  _globals['_RPCSERIALRECEIVEREQUEST']._serialized_start=108
  _globals['_RPCSERIALRECEIVEREQUEST']._serialized_end=152
  _globals['_RPCSERIALRECEIVERESPONSE']._serialized_start=154
  _globals['_RPCSERIALRECEIVERESPONSE']._serialized_end=194
  _globals['_RPCSERIALSTATUSREQUEST']._serialized_start=196
  _globals['_RPCSERIALSTATUSREQUEST']._serialized_end=220
  _globals['_RPCSERIALSTATUS']._serialized_start=222
  _globals['_RPCSERIALSTATUS']._serialized_end=279
  _globals['_RPCSERIAL']._serialized_start=282
  _globals['_RPCSERIAL']._serialized_end=516
# @@protoc_insertion_point(module_scope)