# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import system_pb2 as system__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in system_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SystemServiceStub(object):
    """System information service
    Provides machine configuration and identity information
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemInfo = channel.unary_unary(
                '/beebium.SystemService/GetSystemInfo',
                request_serializer=system__pb2.GetSystemInfoRequest.SerializeToString,
                response_deserializer=system__pb2.SystemInfo.FromString,
                _registered_method=True)
        self.SetMachineName = channel.unary_unary(
                '/beebium.SystemService/SetMachineName',
                request_serializer=system__pb2.SetMachineNameRequest.SerializeToString,
                response_deserializer=system__pb2.SetMachineNameResponse.FromString,
                _registered_method=True)
        self.WatchServerStatus = channel.unary_stream(
                '/beebium.SystemService/WatchServerStatus',
                request_serializer=system__pb2.WatchServerStatusRequest.SerializeToString,
                response_deserializer=system__pb2.ServerStatusEvent.FromString,
                _registered_method=True)
        self.RequestShutdown = channel.unary_unary(
                '/beebium.SystemService/RequestShutdown',
                request_serializer=system__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=system__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.GetAdvertisementState = channel.unary_unary(
                '/beebium.SystemService/GetAdvertisementState',
                request_serializer=system__pb2.GetAdvertisementStateRequest.SerializeToString,
                response_deserializer=system__pb2.GetAdvertisementStateResponse.FromString,
                _registered_method=True)
        self.SetAdvertisement = channel.unary_unary(
                '/beebium.SystemService/SetAdvertisement',
                request_serializer=system__pb2.SetAdvertisementRequest.SerializeToString,
                response_deserializer=system__pb2.SetAdvertisementResponse.FromString,
                _registered_method=True)


class SystemServiceServicer(object):
    """System information service
    Provides machine configuration and identity information
    """

    def GetSystemInfo(self, request, context):
        """Get current system/machine information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMachineName(self, request, context):
        """Set the machine's user-assignable name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchServerStatus(self, request, context):
        """Subscribe to server status events (shutdown notifications, identity changes, etc.)
        Server sends READY immediately upon subscription, then status changes.
        Stream ends when server shuts down or client disconnects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestShutdown(self, request, context):
        """Request server shutdown.
        Returns whether the request was accepted based on shutdown policy.
        Policy: accept if requester's instance UUID matches launch provenance,
        or only one client connected, or --allow-shutdown flag was set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdvertisementState(self, request, context):
        """Get current mDNS service advertisement state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAdvertisement(self, request, context):
        """Enable or disable mDNS service advertisement at runtime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemInfo,
                    request_deserializer=system__pb2.GetSystemInfoRequest.FromString,
                    response_serializer=system__pb2.SystemInfo.SerializeToString,
            ),
            'SetMachineName': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMachineName,
                    request_deserializer=system__pb2.SetMachineNameRequest.FromString,
                    response_serializer=system__pb2.SetMachineNameResponse.SerializeToString,
            ),
            'WatchServerStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchServerStatus,
                    request_deserializer=system__pb2.WatchServerStatusRequest.FromString,
                    response_serializer=system__pb2.ServerStatusEvent.SerializeToString,
            ),
            'RequestShutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestShutdown,
                    request_deserializer=system__pb2.ShutdownRequest.FromString,
                    response_serializer=system__pb2.ShutdownResponse.SerializeToString,
            ),
            'GetAdvertisementState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdvertisementState,
                    request_deserializer=system__pb2.GetAdvertisementStateRequest.FromString,
                    response_serializer=system__pb2.GetAdvertisementStateResponse.SerializeToString,
            ),
            'SetAdvertisement': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAdvertisement,
                    request_deserializer=system__pb2.SetAdvertisementRequest.FromString,
                    response_serializer=system__pb2.SetAdvertisementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.SystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.SystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemService(object):
    """System information service
    Provides machine configuration and identity information
    """

    @staticmethod
    def GetSystemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.SystemService/GetSystemInfo',
            system__pb2.GetSystemInfoRequest.SerializeToString,
            system__pb2.SystemInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMachineName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.SystemService/SetMachineName',
            system__pb2.SetMachineNameRequest.SerializeToString,
            system__pb2.SetMachineNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchServerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/beebium.SystemService/WatchServerStatus',
            system__pb2.WatchServerStatusRequest.SerializeToString,
            system__pb2.ServerStatusEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestShutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.SystemService/RequestShutdown',
            system__pb2.ShutdownRequest.SerializeToString,
            system__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdvertisementState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.SystemService/GetAdvertisementState',
            system__pb2.GetAdvertisementStateRequest.SerializeToString,
            system__pb2.GetAdvertisementStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAdvertisement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.SystemService/SetAdvertisement',
            system__pb2.SetAdvertisementRequest.SerializeToString,
            system__pb2.SetAdvertisementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
