# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: system.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csystem.proto\x12\x07\x62\x65\x65\x62ium\"\x16\n\x14GetSystemInfoRequest\"@\n\nSystemInfo\x12\x14\n\x0cmachine_type\x18\x01 \x01(\t\x12\x1c\n\x14machine_display_name\x18\x02 \x01(\t\"\x1a\n\x18WatchServerStatusRequest\"j\n\x11ServerStatusEvent\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.beebium.ServerStatusType\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x11shutdown_grace_ms\x18\x03 \x01(\r*L\n\x10ServerStatusType\x12\x17\n\x13SERVER_STATUS_READY\x10\x00\x12\x1f\n\x1bSERVER_STATUS_SHUTTING_DOWN\x10\x01\x32\xaa\x01\n\rSystemService\x12\x43\n\rGetSystemInfo\x12\x1d.beebium.GetSystemInfoRequest\x1a\x13.beebium.SystemInfo\x12T\n\x11WatchServerStatus\x12!.beebium.WatchServerStatusRequest\x1a\x1a.beebium.ServerStatusEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERSTATUSTYPE']._serialized_start=251
  _globals['_SERVERSTATUSTYPE']._serialized_end=327
  _globals['_GETSYSTEMINFOREQUEST']._serialized_start=25
  _globals['_GETSYSTEMINFOREQUEST']._serialized_end=47
  _globals['_SYSTEMINFO']._serialized_start=49
  _globals['_SYSTEMINFO']._serialized_end=113
  _globals['_WATCHSERVERSTATUSREQUEST']._serialized_start=115
  _globals['_WATCHSERVERSTATUSREQUEST']._serialized_end=141
  _globals['_SERVERSTATUSEVENT']._serialized_start=143
  _globals['_SERVERSTATUSEVENT']._serialized_end=249
  _globals['_SYSTEMSERVICE']._serialized_start=330
  _globals['_SYSTEMSERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
