# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x07\x62\x65\x65\x62ium\"\x18\n\x16SubscribeFramesRequest\"\xb9\x02\n\x05\x46rame\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\x04\x12\x13\n\x0b\x63ycle_count\x18\x02 \x01(\x04\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x0e\n\x06pixels\x18\x05 \x01(\x0c\x12(\n\x0b\x66ield_order\x18\x06 \x01(\x0e\x32\x13.beebium.FieldOrder\x12\x13\n\x0bleft_border\x18\x07 \x01(\r\x12\x14\n\x0cright_border\x18\x08 \x01(\r\x12\x12\n\ntop_border\x18\t \x01(\r\x12\x15\n\rbottom_border\x18\n \x01(\r\x12\x15\n\rdisplay_width\x18\x0b \x01(\r\x12\x16\n\x0e\x64isplay_height\x18\x0c \x01(\r\x12\'\n\x07regions\x18\r \x03(\x0b\x32\x16.beebium.DisplayRegion\"J\n\rDisplayRegion\x12\x12\n\nstart_line\x18\x01 \x01(\r\x12\x10\n\x08\x65nd_line\x18\x02 \x01(\r\x12\x13\n\x0bpixel_width\x18\x03 \x01(\r\"\x12\n\x10GetConfigRequest\"B\n\x0bVideoConfig\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x14\n\x0c\x66ramerate_hz\x18\x03 \x01(\r*<\n\nFieldOrder\x12\x0f\n\x0bPROGRESSIVE\x10\x00\x12\x0e\n\nEVEN_FIRST\x10\x01\x12\r\n\tODD_FIRST\x10\x02\x32\x92\x01\n\x0cVideoService\x12\x44\n\x0fSubscribeFrames\x12\x1f.beebium.SubscribeFramesRequest\x1a\x0e.beebium.Frame0\x01\x12<\n\tGetConfig\x12\x19.beebium.GetConfigRequest\x1a\x14.beebium.VideoConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIELDORDER']._serialized_start=530
  _globals['_FIELDORDER']._serialized_end=590
  _globals['_SUBSCRIBEFRAMESREQUEST']._serialized_start=24
  _globals['_SUBSCRIBEFRAMESREQUEST']._serialized_end=48
  _globals['_FRAME']._serialized_start=51
  _globals['_FRAME']._serialized_end=364
  _globals['_DISPLAYREGION']._serialized_start=366
  _globals['_DISPLAYREGION']._serialized_end=440
  _globals['_GETCONFIGREQUEST']._serialized_start=442
  _globals['_GETCONFIGREQUEST']._serialized_end=460
  _globals['_VIDEOCONFIG']._serialized_start=462
  _globals['_VIDEOCONFIG']._serialized_end=528
  _globals['_VIDEOSERVICE']._serialized_start=593
  _globals['_VIDEOSERVICE']._serialized_end=739
# @@protoc_insertion_point(module_scope)
