# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
from . import piconet_service_pb2 as _piconet_service_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class PiconetServiceStub:
    """Piconet-specific service. Lives alongside PiconetEconetTransportExtension
    in src/extensions/piconet/ and is served via that extension's
    PiconetDispatcher over the core's ExtensionRpc channel (no gRPC stub is
    compiled from this service block). It is reachable only when Piconet is
    the active transport.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for Piconet (the USB serial bridge to a real Econet wire) lives here.

    Initial scope is intentionally minimal -- just enough for a user
    to confirm "yes, my Piconet is plugged in, and it's on /dev/X".
    Once the service exists it can grow without further architectural
    work; expansion possibilities are listed at the bottom of this file.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> PiconetServiceAsyncStub: ...
    GetStatus: _grpc.UnaryUnaryMultiCallable[_piconet_service_pb2.PiconetGetStatusRequest, _piconet_service_pb2.PiconetGetStatusResponse]
    """Read the current Piconet adapter state. Returns immediately;
    does not touch the serial wire.
    """

@_typing.type_check_only
class PiconetServiceAsyncStub(PiconetServiceStub):
    """Piconet-specific service. Lives alongside PiconetEconetTransportExtension
    in src/extensions/piconet/ and is served via that extension's
    PiconetDispatcher over the core's ExtensionRpc channel (no gRPC stub is
    compiled from this service block). It is reachable only when Piconet is
    the active transport.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for Piconet (the USB serial bridge to a real Econet wire) lives here.

    Initial scope is intentionally minimal -- just enough for a user
    to confirm "yes, my Piconet is plugged in, and it's on /dev/X".
    Once the service exists it can grow without further architectural
    work; expansion possibilities are listed at the bottom of this file.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetStatus: _aio.UnaryUnaryMultiCallable[_piconet_service_pb2.PiconetGetStatusRequest, _piconet_service_pb2.PiconetGetStatusResponse]  # type: ignore[assignment]
    """Read the current Piconet adapter state. Returns immediately;
    does not touch the serial wire.
    """

class PiconetServiceServicer(metaclass=_abc_1.ABCMeta):
    """Piconet-specific service. Lives alongside PiconetEconetTransportExtension
    in src/extensions/piconet/ and is served via that extension's
    PiconetDispatcher over the core's ExtensionRpc channel (no gRPC stub is
    compiled from this service block). It is reachable only when Piconet is
    the active transport.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for Piconet (the USB serial bridge to a real Econet wire) lives here.

    Initial scope is intentionally minimal -- just enough for a user
    to confirm "yes, my Piconet is plugged in, and it's on /dev/X".
    Once the service exists it can grow without further architectural
    work; expansion possibilities are listed at the bottom of this file.
    """

    @_abc_1.abstractmethod
    def GetStatus(
        self,
        request: _piconet_service_pb2.PiconetGetStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_piconet_service_pb2.PiconetGetStatusResponse, _abc.Awaitable[_piconet_service_pb2.PiconetGetStatusResponse]]:
        """Read the current Piconet adapter state. Returns immediately;
        does not touch the serial wire.
        """

def add_PiconetServiceServicer_to_server(servicer: PiconetServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...