# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PiconetGetStatusRequest(_message.Message):
    """--- Status ---

    Empty.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PiconetGetStatusRequest: _TypeAlias = PiconetGetStatusRequest  # noqa: Y015

@_typing.final
class PiconetGetStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_PATH_FIELD_NUMBER: _builtins.int
    SERIAL_OPEN_FIELD_NUMBER: _builtins.int
    device_path: _builtins.str
    """The serial device path the Piconet is configured to use, e.g.
    "/dev/tty.usbmodem101". Set at startup from the
    --piconet device_path=... CLI argument or preset value.
    """
    serial_open: _builtins.bool
    """True if the SerialPort is currently open. On POSIX this means
    the file descriptor is valid; if the user yanks the USB cable
    mid-run this transitions to false. False on startup means the
    device couldn't be opened (e.g. wrong path, not plugged in).

    This says nothing about whether a real Econet wire is connected
    to the Piconet adapter, only whether the host-side USB CDC
    endpoint is responsive. See "Future RPCs" below for clock /
    wire-activity detection.
    """
    def __init__(
        self,
        *,
        device_path: _builtins.str = ...,
        serial_open: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_path", b"device_path", "serial_open", b"serial_open"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PiconetGetStatusResponse: _TypeAlias = PiconetGetStatusResponse  # noqa: Y015